#!/bin/bash
#SBATCH --partition=SP2
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=8
#SBATCH -J lloyd_diamond_tax_extra_SiaM_1.sh
#SBATCH --mem=24042
#SBATCH --time=172:00:00
#OpenMP settings:
export OMP_NUM_THREADS=1
export MKL_NUM_THREADS=1
export OMP_PLACES=threads
export OMP_PROC_BIND=spread
echo $SLURM_JOB_ID
echo $SLURM_SUBMIT_DIR
echo $SLURM_JOB_NODELIST

srun diamond blastp -q ../aligned_proteins_extra/SRR5983412_SiaM_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5983412_SiaM_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins_extra/SRR5947833_SiaM_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5947833_SiaM_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins_extra/SRR5983391_SiaM_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5983391_SiaM_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins_extra/SRR5983393_SiaM_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5983393_SiaM_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins_extra/SRR5947823_SiaM_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5947823_SiaM_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins_extra/SRR5947868_SiaM_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5947868_SiaM_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins_extra/SRR5983308_SiaM_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5983308_SiaM_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins_extra/SRR5947839_SiaM_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5947839_SiaM_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins_extra/SRR5983472_SiaM_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5983472_SiaM_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins_extra/SRR5983469_SiaM_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5983469_SiaM_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins_extra/SRR5983448_SiaM_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5983448_SiaM_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins_extra/SRR5983279_SiaM_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5983279_SiaM_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins_extra/SRR5983275_SiaM_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5983275_SiaM_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins_extra/SRR5983446_SiaM_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5983446_SiaM_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins_extra/SRR5983422_SiaM_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5983422_SiaM_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins_extra/SRR5983441_SiaM_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5983441_SiaM_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins_extra/SRR5983386_SiaM_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5983386_SiaM_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins_extra/SRR5983459_SiaM_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5983459_SiaM_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins_extra/SRR5983360_SiaM_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5983360_SiaM_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins_extra/SRR5983377_SiaM_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5983377_SiaM_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins_extra/SRR5983367_SiaM_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5983367_SiaM_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins_extra/SRR5983365_SiaM_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5983365_SiaM_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins_extra/SRR5983283_SiaM_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5983283_SiaM_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins_extra/SRR5983289_SiaM_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5983289_SiaM_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins_extra/SRR5983294_SiaM_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5983294_SiaM_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins_extra/SRR5983264_SiaM_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5983264_SiaM_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins_extra/SRR5947815_SiaM_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5947815_SiaM_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins_extra/SRR5947832_SiaM_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5947832_SiaM_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins_extra/SRR5983418_SiaM_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5983418_SiaM_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins_extra/SRR5947825_SiaM_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5947825_SiaM_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins_extra/SRR5947858_SiaM_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5947858_SiaM_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins_extra/SRR5983342_SiaM_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5983342_SiaM_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins_extra/SRR5983272_SiaM_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5983272_SiaM_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins_extra/SRR5983427_SiaM_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5983427_SiaM_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins_extra/SRR5983326_SiaM_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5983326_SiaM_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins_extra/SRR5983314_SiaM_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5983314_SiaM_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins_extra/SRR5947819_SiaM_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5947819_SiaM_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins_extra/SRR5947827_SiaM_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5947827_SiaM_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins_extra/SRR5947843_SiaM_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5947843_SiaM_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins_extra/SRR5983346_SiaM_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5983346_SiaM_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins_extra/SRR5947850_SiaM_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5947850_SiaM_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins_extra/SRR5947851_SiaM_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5947851_SiaM_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins_extra/SRR5947883_SiaM_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5947883_SiaM_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins_extra/SRR5983304_SiaM_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5983304_SiaM_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins_extra/SRR5983462_SiaM_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5983462_SiaM_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins_extra/SRR5983280_SiaM_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5983280_SiaM_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins_extra/SRR5983470_SiaM_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5983470_SiaM_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins_extra/SRR5983480_SiaM_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5983480_SiaM_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins_extra/SRR5983484_SiaM_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5983484_SiaM_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins_extra/SRR5983273_SiaM_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5983273_SiaM_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins_extra/SRR5983423_SiaM_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5983423_SiaM_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins_extra/SRR5983438_SiaM_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5983438_SiaM_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins_extra/SRR5983372_SiaM_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5983372_SiaM_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins_extra/SRR5983400_SiaM_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5983400_SiaM_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins_extra/SRR5983331_SiaM_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5983331_SiaM_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins_extra/SRR5983325_SiaM_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5983325_SiaM_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins_extra/SRR5983355_SiaM_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5983355_SiaM_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins_extra/SRR5983284_SiaM_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5983284_SiaM_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins_extra/SRR5983291_SiaM_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5983291_SiaM_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins_extra/SRR5983411_SiaM_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5983411_SiaM_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins_extra/SRR5947813_SiaM_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5947813_SiaM_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins_extra/SRR5947809_SiaM_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5947809_SiaM_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins_extra/SRR5947818_SiaM_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5947818_SiaM_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins_extra/SRR5947816_SiaM_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5947816_SiaM_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins_extra/SRR5947837_SiaM_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5947837_SiaM_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins_extra/SRR5947831_SiaM_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5947831_SiaM_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins_extra/SRR5983479_SiaM_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5983479_SiaM_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins_extra/SRR5947822_SiaM_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5947822_SiaM_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins_extra/SRR5983481_SiaM_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5983481_SiaM_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins_extra/SRR5983276_SiaM_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5983276_SiaM_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins_extra/SRR5983428_SiaM_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5983428_SiaM_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins_extra/SRR5983382_SiaM_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5983382_SiaM_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins_extra/SRR5983376_SiaM_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5983376_SiaM_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins_extra/SRR5983403_SiaM_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5983403_SiaM_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins_extra/SRR5983299_SiaM_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5983299_SiaM_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins_extra/SRR5983357_SiaM_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5983357_SiaM_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins_extra/SRR5983297_SiaM_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5983297_SiaM_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins_extra/SRR5983267_SiaM_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5983267_SiaM_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins_extra/SRR5983301_SiaM_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5983301_SiaM_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins_extra/SRR5983282_SiaM_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5983282_SiaM_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins_extra/SRR5983474_SiaM_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5983474_SiaM_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins_extra/SRR5983292_SiaM_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5983292_SiaM_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins_extra/SRR5983450_SiaM_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5983450_SiaM_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins_extra/SRR5983268_SiaM_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5983268_SiaM_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins_extra/SRR5983434_SiaM_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5983434_SiaM_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins_extra/SRR5983384_SiaM_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5983384_SiaM_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins_extra/SRR5983431_SiaM_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5983431_SiaM_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins_extra/SRR5983405_SiaM_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5983405_SiaM_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins_extra/SRR5983329_SiaM_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5983329_SiaM_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins_extra/SRR5983296_SiaM_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5983296_SiaM_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
