#!/bin/bash
#SBATCH --partition=SP2
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=8
#SBATCH -J kim_diamond_tax_SiaP.sh
#SBATCH --mem=24042
#SBATCH --time=172:00:00
#OpenMP settings:
export OMP_NUM_THREADS=1
export MKL_NUM_THREADS=1
export OMP_PLACES=threads
export OMP_PROC_BIND=spread
echo $SLURM_JOB_ID
echo $SLURM_SUBMIT_DIR
echo $SLURM_JOB_NODELIST

srun diamond blastp -q ../aligned_proteins/ERR3607252_SiaP_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o ERR3607252_SiaP_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/ERR3607253_SiaP_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o ERR3607253_SiaP_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/ERR3607254_SiaP_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o ERR3607254_SiaP_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/ERR3607255_SiaP_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o ERR3607255_SiaP_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/ERR3607256_SiaP_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o ERR3607256_SiaP_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/ERR3607257_SiaP_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o ERR3607257_SiaP_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/ERR3607258_SiaP_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o ERR3607258_SiaP_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/ERR3607259_SiaP_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o ERR3607259_SiaP_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/ERR3607260_SiaP_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o ERR3607260_SiaP_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/ERR3607261_SiaP_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o ERR3607261_SiaP_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/ERR3607262_SiaP_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o ERR3607262_SiaP_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/ERR3607263_SiaP_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o ERR3607263_SiaP_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/ERR3607264_SiaP_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o ERR3607264_SiaP_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/ERR3607265_SiaP_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o ERR3607265_SiaP_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/ERR3607266_SiaP_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o ERR3607266_SiaP_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/ERR3607267_SiaP_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o ERR3607267_SiaP_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/ERR3607268_SiaP_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o ERR3607268_SiaP_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/ERR3607269_SiaP_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o ERR3607269_SiaP_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/ERR3607270_SiaP_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o ERR3607270_SiaP_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/ERR3607271_SiaP_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o ERR3607271_SiaP_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/ERR3607272_SiaP_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o ERR3607272_SiaP_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/ERR3607273_SiaP_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o ERR3607273_SiaP_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/ERR3607274_SiaP_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o ERR3607274_SiaP_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/ERR3607275_SiaP_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o ERR3607275_SiaP_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/ERR3607276_SiaP_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o ERR3607276_SiaP_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/ERR3607277_SiaP_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o ERR3607277_SiaP_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/ERR3607278_SiaP_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o ERR3607278_SiaP_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/ERR3607279_SiaP_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o ERR3607279_SiaP_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/ERR3607280_SiaP_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o ERR3607280_SiaP_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/ERR3607281_SiaP_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o ERR3607281_SiaP_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/ERR3607282_SiaP_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o ERR3607282_SiaP_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/ERR3607283_SiaP_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o ERR3607283_SiaP_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/ERR3607284_SiaP_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o ERR3607284_SiaP_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/ERR3607285_SiaP_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o ERR3607285_SiaP_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/ERR3607286_SiaP_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o ERR3607286_SiaP_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/ERR3607287_SiaP_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o ERR3607287_SiaP_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/ERR3607288_SiaP_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o ERR3607288_SiaP_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/ERR3607289_SiaP_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o ERR3607289_SiaP_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/ERR3607290_SiaP_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o ERR3607290_SiaP_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/ERR3607291_SiaP_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o ERR3607291_SiaP_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/ERR3607292_SiaP_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o ERR3607292_SiaP_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/ERR3607293_SiaP_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o ERR3607293_SiaP_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/ERR3607294_SiaP_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o ERR3607294_SiaP_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/ERR3607295_SiaP_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o ERR3607295_SiaP_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/ERR3607296_SiaP_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o ERR3607296_SiaP_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/ERR3607297_SiaP_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o ERR3607297_SiaP_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/ERR3607298_SiaP_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o ERR3607298_SiaP_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/ERR3607299_SiaP_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o ERR3607299_SiaP_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/ERR3607300_SiaP_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o ERR3607300_SiaP_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/ERR3607301_SiaP_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o ERR3607301_SiaP_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/ERR3607302_SiaP_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o ERR3607302_SiaP_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/ERR3607303_SiaP_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o ERR3607303_SiaP_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/ERR3607304_SiaP_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o ERR3607304_SiaP_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/ERR3607305_SiaP_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o ERR3607305_SiaP_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/ERR3607306_SiaP_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o ERR3607306_SiaP_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/ERR3607307_SiaP_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o ERR3607307_SiaP_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/ERR3607308_SiaP_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o ERR3607308_SiaP_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/ERR3607309_SiaP_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o ERR3607309_SiaP_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/ERR3607310_SiaP_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o ERR3607310_SiaP_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/ERR3607311_SiaP_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o ERR3607311_SiaP_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/ERR3607312_SiaP_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o ERR3607312_SiaP_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
