#!/bin/bash
#SBATCH --partition=SP2
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=8
#SBATCH -J kim_diamond_tax_KpsC.sh
#SBATCH --mem=24042
#SBATCH --time=172:00:00
#OpenMP settings:
export OMP_NUM_THREADS=1
export MKL_NUM_THREADS=1
export OMP_PLACES=threads
export OMP_PROC_BIND=spread
echo $SLURM_JOB_ID
echo $SLURM_SUBMIT_DIR
echo $SLURM_JOB_NODELIST

srun diamond blastp -q ../aligned_proteins/ERR3607252_KpsC_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o ERR3607252_KpsC_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/ERR3607253_KpsC_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o ERR3607253_KpsC_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/ERR3607254_KpsC_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o ERR3607254_KpsC_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/ERR3607255_KpsC_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o ERR3607255_KpsC_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/ERR3607256_KpsC_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o ERR3607256_KpsC_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/ERR3607257_KpsC_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o ERR3607257_KpsC_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/ERR3607258_KpsC_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o ERR3607258_KpsC_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/ERR3607259_KpsC_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o ERR3607259_KpsC_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/ERR3607260_KpsC_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o ERR3607260_KpsC_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/ERR3607261_KpsC_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o ERR3607261_KpsC_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/ERR3607262_KpsC_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o ERR3607262_KpsC_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/ERR3607263_KpsC_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o ERR3607263_KpsC_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/ERR3607264_KpsC_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o ERR3607264_KpsC_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/ERR3607265_KpsC_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o ERR3607265_KpsC_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/ERR3607266_KpsC_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o ERR3607266_KpsC_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/ERR3607267_KpsC_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o ERR3607267_KpsC_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/ERR3607268_KpsC_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o ERR3607268_KpsC_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/ERR3607269_KpsC_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o ERR3607269_KpsC_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/ERR3607270_KpsC_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o ERR3607270_KpsC_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/ERR3607271_KpsC_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o ERR3607271_KpsC_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/ERR3607272_KpsC_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o ERR3607272_KpsC_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/ERR3607273_KpsC_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o ERR3607273_KpsC_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/ERR3607274_KpsC_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o ERR3607274_KpsC_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/ERR3607275_KpsC_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o ERR3607275_KpsC_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/ERR3607276_KpsC_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o ERR3607276_KpsC_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/ERR3607277_KpsC_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o ERR3607277_KpsC_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/ERR3607278_KpsC_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o ERR3607278_KpsC_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/ERR3607279_KpsC_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o ERR3607279_KpsC_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/ERR3607280_KpsC_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o ERR3607280_KpsC_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/ERR3607281_KpsC_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o ERR3607281_KpsC_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/ERR3607282_KpsC_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o ERR3607282_KpsC_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/ERR3607283_KpsC_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o ERR3607283_KpsC_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/ERR3607284_KpsC_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o ERR3607284_KpsC_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/ERR3607285_KpsC_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o ERR3607285_KpsC_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/ERR3607286_KpsC_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o ERR3607286_KpsC_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/ERR3607287_KpsC_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o ERR3607287_KpsC_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/ERR3607288_KpsC_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o ERR3607288_KpsC_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/ERR3607289_KpsC_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o ERR3607289_KpsC_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/ERR3607290_KpsC_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o ERR3607290_KpsC_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/ERR3607291_KpsC_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o ERR3607291_KpsC_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/ERR3607292_KpsC_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o ERR3607292_KpsC_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/ERR3607293_KpsC_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o ERR3607293_KpsC_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/ERR3607294_KpsC_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o ERR3607294_KpsC_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/ERR3607295_KpsC_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o ERR3607295_KpsC_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/ERR3607296_KpsC_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o ERR3607296_KpsC_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/ERR3607297_KpsC_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o ERR3607297_KpsC_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/ERR3607298_KpsC_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o ERR3607298_KpsC_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/ERR3607299_KpsC_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o ERR3607299_KpsC_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/ERR3607300_KpsC_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o ERR3607300_KpsC_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/ERR3607301_KpsC_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o ERR3607301_KpsC_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/ERR3607302_KpsC_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o ERR3607302_KpsC_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/ERR3607303_KpsC_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o ERR3607303_KpsC_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/ERR3607304_KpsC_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o ERR3607304_KpsC_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/ERR3607305_KpsC_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o ERR3607305_KpsC_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/ERR3607306_KpsC_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o ERR3607306_KpsC_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/ERR3607307_KpsC_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o ERR3607307_KpsC_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/ERR3607308_KpsC_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o ERR3607308_KpsC_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/ERR3607309_KpsC_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o ERR3607309_KpsC_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/ERR3607310_KpsC_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o ERR3607310_KpsC_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/ERR3607311_KpsC_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o ERR3607311_KpsC_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/ERR3607312_KpsC_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o ERR3607312_KpsC_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
