#!/bin/bash
#SBATCH --partition=SP2
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=8
#SBATCH -J lloyd_diamond_tax_KpsD_1.sh
#SBATCH --mem=24042
#SBATCH --time=172:00:00
#OpenMP settings:
export OMP_NUM_THREADS=1
export MKL_NUM_THREADS=1
export OMP_PLACES=threads
export OMP_PROC_BIND=spread
echo $SLURM_JOB_ID
echo $SLURM_SUBMIT_DIR
echo $SLURM_JOB_NODELIST

srun diamond blastp -q ../aligned_proteins/SRR5983412_KpsD_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5983412_KpsD_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5947833_KpsD_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5947833_KpsD_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5983391_KpsD_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5983391_KpsD_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5983393_KpsD_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5983393_KpsD_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5947823_KpsD_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5947823_KpsD_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5947868_KpsD_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5947868_KpsD_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5983308_KpsD_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5983308_KpsD_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5947839_KpsD_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5947839_KpsD_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5983472_KpsD_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5983472_KpsD_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5983469_KpsD_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5983469_KpsD_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5983448_KpsD_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5983448_KpsD_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5983279_KpsD_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5983279_KpsD_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5983275_KpsD_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5983275_KpsD_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5983446_KpsD_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5983446_KpsD_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5983422_KpsD_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5983422_KpsD_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5983441_KpsD_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5983441_KpsD_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5983386_KpsD_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5983386_KpsD_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5983459_KpsD_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5983459_KpsD_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5983360_KpsD_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5983360_KpsD_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5983377_KpsD_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5983377_KpsD_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5983367_KpsD_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5983367_KpsD_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5983365_KpsD_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5983365_KpsD_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5983283_KpsD_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5983283_KpsD_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5983289_KpsD_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5983289_KpsD_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5983294_KpsD_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5983294_KpsD_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5983264_KpsD_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5983264_KpsD_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5947815_KpsD_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5947815_KpsD_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5947832_KpsD_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5947832_KpsD_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5983418_KpsD_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5983418_KpsD_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5947825_KpsD_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5947825_KpsD_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5947858_KpsD_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5947858_KpsD_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5983342_KpsD_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5983342_KpsD_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5983272_KpsD_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5983272_KpsD_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5983427_KpsD_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5983427_KpsD_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5983326_KpsD_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5983326_KpsD_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5983314_KpsD_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5983314_KpsD_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5947819_KpsD_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5947819_KpsD_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5947827_KpsD_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5947827_KpsD_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5947843_KpsD_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5947843_KpsD_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5983346_KpsD_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5983346_KpsD_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5947850_KpsD_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5947850_KpsD_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5947851_KpsD_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5947851_KpsD_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5947883_KpsD_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5947883_KpsD_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5983304_KpsD_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5983304_KpsD_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5983462_KpsD_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5983462_KpsD_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5983280_KpsD_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5983280_KpsD_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5983470_KpsD_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5983470_KpsD_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5983480_KpsD_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5983480_KpsD_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5983484_KpsD_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5983484_KpsD_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5983273_KpsD_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5983273_KpsD_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5983423_KpsD_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5983423_KpsD_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5983438_KpsD_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5983438_KpsD_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5983372_KpsD_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5983372_KpsD_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5983400_KpsD_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5983400_KpsD_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5983331_KpsD_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5983331_KpsD_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5983325_KpsD_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5983325_KpsD_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5983355_KpsD_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5983355_KpsD_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5983284_KpsD_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5983284_KpsD_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5983291_KpsD_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5983291_KpsD_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5983411_KpsD_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5983411_KpsD_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5947813_KpsD_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5947813_KpsD_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5947809_KpsD_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5947809_KpsD_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5947818_KpsD_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5947818_KpsD_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5947816_KpsD_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5947816_KpsD_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5947837_KpsD_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5947837_KpsD_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5947831_KpsD_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5947831_KpsD_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5983479_KpsD_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5983479_KpsD_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5947822_KpsD_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5947822_KpsD_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5983481_KpsD_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5983481_KpsD_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5983276_KpsD_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5983276_KpsD_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5983428_KpsD_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5983428_KpsD_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5983382_KpsD_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5983382_KpsD_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5983376_KpsD_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5983376_KpsD_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5983403_KpsD_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5983403_KpsD_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5983299_KpsD_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5983299_KpsD_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5983357_KpsD_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5983357_KpsD_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5983297_KpsD_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5983297_KpsD_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5983267_KpsD_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5983267_KpsD_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5983301_KpsD_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5983301_KpsD_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5983282_KpsD_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5983282_KpsD_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5983474_KpsD_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5983474_KpsD_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5983292_KpsD_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5983292_KpsD_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5983450_KpsD_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5983450_KpsD_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5983268_KpsD_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5983268_KpsD_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5983434_KpsD_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5983434_KpsD_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5983384_KpsD_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5983384_KpsD_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5983431_KpsD_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5983431_KpsD_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5983405_KpsD_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5983405_KpsD_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5983329_KpsD_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5983329_KpsD_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5983296_KpsD_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5983296_KpsD_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
