#!/bin/bash
#SBATCH --partition=SP2
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=8
#SBATCH -J lloyd_diamond_tax_NeuS_1.sh
#SBATCH --mem=24042
#SBATCH --time=172:00:00
#OpenMP settings:
export OMP_NUM_THREADS=1
export MKL_NUM_THREADS=1
export OMP_PLACES=threads
export OMP_PROC_BIND=spread
echo $SLURM_JOB_ID
echo $SLURM_SUBMIT_DIR
echo $SLURM_JOB_NODELIST

srun diamond blastp -q ../aligned_proteins/SRR5935740_NeuS_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5935740_NeuS_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5935741_NeuS_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5935741_NeuS_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5935742_NeuS_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5935742_NeuS_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5935743_NeuS_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5935743_NeuS_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5935744_NeuS_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5935744_NeuS_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5935745_NeuS_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5935745_NeuS_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5935746_NeuS_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5935746_NeuS_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5935747_NeuS_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5935747_NeuS_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5935748_NeuS_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5935748_NeuS_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5935749_NeuS_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5935749_NeuS_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5935750_NeuS_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5935750_NeuS_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5935751_NeuS_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5935751_NeuS_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5935752_NeuS_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5935752_NeuS_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5935753_NeuS_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5935753_NeuS_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5935754_NeuS_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5935754_NeuS_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5935755_NeuS_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5935755_NeuS_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5935756_NeuS_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5935756_NeuS_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5935757_NeuS_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5935757_NeuS_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5935758_NeuS_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5935758_NeuS_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5935759_NeuS_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5935759_NeuS_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5935760_NeuS_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5935760_NeuS_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5935761_NeuS_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5935761_NeuS_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5935762_NeuS_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5935762_NeuS_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5935763_NeuS_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5935763_NeuS_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5935764_NeuS_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5935764_NeuS_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5935765_NeuS_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5935765_NeuS_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5935766_NeuS_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5935766_NeuS_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5935767_NeuS_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5935767_NeuS_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5935768_NeuS_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5935768_NeuS_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5935769_NeuS_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5935769_NeuS_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5935770_NeuS_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5935770_NeuS_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5935771_NeuS_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5935771_NeuS_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5935772_NeuS_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5935772_NeuS_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5935773_NeuS_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5935773_NeuS_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5935774_NeuS_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5935774_NeuS_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5935775_NeuS_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5935775_NeuS_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5935776_NeuS_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5935776_NeuS_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5935777_NeuS_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5935777_NeuS_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5935778_NeuS_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5935778_NeuS_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5935779_NeuS_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5935779_NeuS_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5935780_NeuS_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5935780_NeuS_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5935781_NeuS_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5935781_NeuS_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5935782_NeuS_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5935782_NeuS_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5935783_NeuS_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5935783_NeuS_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5935784_NeuS_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5935784_NeuS_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5935785_NeuS_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5935785_NeuS_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5935786_NeuS_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5935786_NeuS_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5935787_NeuS_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5935787_NeuS_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5935788_NeuS_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5935788_NeuS_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5935789_NeuS_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5935789_NeuS_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
