#!/bin/bash
#SBATCH --partition=SP2
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=8
#SBATCH -J lloyd_diamond_tax_Lst_2.sh
#SBATCH --mem=24042
#SBATCH --time=172:00:00
#OpenMP settings:
export OMP_NUM_THREADS=1
export MKL_NUM_THREADS=1
export OMP_PLACES=threads
export OMP_PROC_BIND=spread
echo $SLURM_JOB_ID
echo $SLURM_SUBMIT_DIR
echo $SLURM_JOB_NODELIST

srun diamond blastp -q ../aligned_proteins/SRR5935790_Lst_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5935790_Lst_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5935791_Lst_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5935791_Lst_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5935792_Lst_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5935792_Lst_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5935793_Lst_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5935793_Lst_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5935794_Lst_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5935794_Lst_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5935795_Lst_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5935795_Lst_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5935796_Lst_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5935796_Lst_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5935797_Lst_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5935797_Lst_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5935798_Lst_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5935798_Lst_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5935799_Lst_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5935799_Lst_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5935800_Lst_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5935800_Lst_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5935801_Lst_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5935801_Lst_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5935802_Lst_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5935802_Lst_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5935803_Lst_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5935803_Lst_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5935804_Lst_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5935804_Lst_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5935805_Lst_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5935805_Lst_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5935806_Lst_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5935806_Lst_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5935807_Lst_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5935807_Lst_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5935808_Lst_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5935808_Lst_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5935809_Lst_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5935809_Lst_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5935810_Lst_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5935810_Lst_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5935811_Lst_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5935811_Lst_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5935812_Lst_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5935812_Lst_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5935813_Lst_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5935813_Lst_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5935814_Lst_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5935814_Lst_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5935815_Lst_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5935815_Lst_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5935816_Lst_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5935816_Lst_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5935817_Lst_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5935817_Lst_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5935818_Lst_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5935818_Lst_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5935819_Lst_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5935819_Lst_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5935820_Lst_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5935820_Lst_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5935821_Lst_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5935821_Lst_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5935822_Lst_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5935822_Lst_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5935823_Lst_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5935823_Lst_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5935824_Lst_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5935824_Lst_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5935825_Lst_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5935825_Lst_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5935826_Lst_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5935826_Lst_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5935827_Lst_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5935827_Lst_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5935828_Lst_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5935828_Lst_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5935829_Lst_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5935829_Lst_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5935830_Lst_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5935830_Lst_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5935831_Lst_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5935831_Lst_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5935832_Lst_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5935832_Lst_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5935833_Lst_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5935833_Lst_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5935834_Lst_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5935834_Lst_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5935835_Lst_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5935835_Lst_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5935836_Lst_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5935836_Lst_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5935837_Lst_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5935837_Lst_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5935838_Lst_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5935838_Lst_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5935839_Lst_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5935839_Lst_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
