#!/bin/bash
#SBATCH --partition=SP2
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=8
#SBATCH -J lloyd_diamond_tax_NeuD_18.sh
#SBATCH --mem=24042
#SBATCH --time=172:00:00
#OpenMP settings:
export OMP_NUM_THREADS=1
export MKL_NUM_THREADS=1
export OMP_PLACES=threads
export OMP_PROC_BIND=spread
echo $SLURM_JOB_ID
echo $SLURM_SUBMIT_DIR
echo $SLURM_JOB_NODELIST

srun diamond blastp -q ../aligned_proteins/SRR5946955_NeuD_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5946955_NeuD_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5946956_NeuD_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5946956_NeuD_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5946957_NeuD_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5946957_NeuD_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5946958_NeuD_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5946958_NeuD_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5946959_NeuD_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5946959_NeuD_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5946960_NeuD_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5946960_NeuD_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5946961_NeuD_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5946961_NeuD_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5946962_NeuD_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5946962_NeuD_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5946963_NeuD_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5946963_NeuD_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5946964_NeuD_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5946964_NeuD_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5946965_NeuD_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5946965_NeuD_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5946966_NeuD_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5946966_NeuD_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5946967_NeuD_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5946967_NeuD_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5946968_NeuD_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5946968_NeuD_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5946969_NeuD_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5946969_NeuD_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5946970_NeuD_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5946970_NeuD_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5946971_NeuD_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5946971_NeuD_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5946972_NeuD_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5946972_NeuD_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5946973_NeuD_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5946973_NeuD_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5946974_NeuD_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5946974_NeuD_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5946975_NeuD_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5946975_NeuD_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5946976_NeuD_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5946976_NeuD_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5946977_NeuD_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5946977_NeuD_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5946978_NeuD_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5946978_NeuD_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5946979_NeuD_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5946979_NeuD_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5946980_NeuD_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5946980_NeuD_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5946981_NeuD_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5946981_NeuD_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5946982_NeuD_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5946982_NeuD_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5946983_NeuD_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5946983_NeuD_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5946984_NeuD_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5946984_NeuD_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5946985_NeuD_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5946985_NeuD_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5946986_NeuD_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5946986_NeuD_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5946987_NeuD_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5946987_NeuD_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5946988_NeuD_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5946988_NeuD_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5946989_NeuD_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5946989_NeuD_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5946990_NeuD_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5946990_NeuD_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5946991_NeuD_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5946991_NeuD_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5946992_NeuD_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5946992_NeuD_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5946993_NeuD_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5946993_NeuD_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5946994_NeuD_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5946994_NeuD_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5946995_NeuD_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5946995_NeuD_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5946996_NeuD_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5946996_NeuD_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5946997_NeuD_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5946997_NeuD_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5946998_NeuD_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5946998_NeuD_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5946999_NeuD_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5946999_NeuD_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5947000_NeuD_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5947000_NeuD_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5947001_NeuD_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5947001_NeuD_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5947002_NeuD_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5947002_NeuD_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5947003_NeuD_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5947003_NeuD_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5947004_NeuD_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5947004_NeuD_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
