#!/bin/bash
#SBATCH --partition=SP2
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=8
#SBATCH -J lloyd_diamond_tax_SiaP_20.sh
#SBATCH --mem=24042
#SBATCH --time=172:00:00
#OpenMP settings:
export OMP_NUM_THREADS=1
export MKL_NUM_THREADS=1
export OMP_PLACES=threads
export OMP_PROC_BIND=spread
echo $SLURM_JOB_ID
echo $SLURM_SUBMIT_DIR
echo $SLURM_JOB_NODELIST

srun diamond blastp -q ../aligned_proteins/SRR5947055_SiaP_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5947055_SiaP_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5947056_SiaP_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5947056_SiaP_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5947057_SiaP_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5947057_SiaP_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5947058_SiaP_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5947058_SiaP_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5947059_SiaP_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5947059_SiaP_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5947060_SiaP_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5947060_SiaP_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5947061_SiaP_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5947061_SiaP_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5947062_SiaP_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5947062_SiaP_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5947063_SiaP_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5947063_SiaP_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5947064_SiaP_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5947064_SiaP_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5947065_SiaP_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5947065_SiaP_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5947066_SiaP_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5947066_SiaP_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5947067_SiaP_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5947067_SiaP_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5947068_SiaP_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5947068_SiaP_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5947069_SiaP_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5947069_SiaP_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5947070_SiaP_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5947070_SiaP_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5947071_SiaP_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5947071_SiaP_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5947072_SiaP_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5947072_SiaP_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5947073_SiaP_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5947073_SiaP_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5947074_SiaP_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5947074_SiaP_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5947075_SiaP_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5947075_SiaP_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5947076_SiaP_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5947076_SiaP_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5947077_SiaP_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5947077_SiaP_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5947078_SiaP_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5947078_SiaP_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5947079_SiaP_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5947079_SiaP_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5947080_SiaP_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5947080_SiaP_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5947081_SiaP_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5947081_SiaP_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5947082_SiaP_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5947082_SiaP_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5947083_SiaP_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5947083_SiaP_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5947084_SiaP_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5947084_SiaP_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5947085_SiaP_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5947085_SiaP_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5947086_SiaP_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5947086_SiaP_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5947087_SiaP_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5947087_SiaP_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5947088_SiaP_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5947088_SiaP_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5947089_SiaP_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5947089_SiaP_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5947090_SiaP_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5947090_SiaP_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5947091_SiaP_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5947091_SiaP_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5947092_SiaP_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5947092_SiaP_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5947093_SiaP_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5947093_SiaP_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5947094_SiaP_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5947094_SiaP_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5947095_SiaP_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5947095_SiaP_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5947096_SiaP_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5947096_SiaP_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5947097_SiaP_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5947097_SiaP_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5947098_SiaP_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5947098_SiaP_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5947099_SiaP_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5947099_SiaP_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5947100_SiaP_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5947100_SiaP_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5947101_SiaP_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5947101_SiaP_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5947102_SiaP_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5947102_SiaP_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5947103_SiaP_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5947103_SiaP_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5947104_SiaP_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5947104_SiaP_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
