#!/bin/bash
#SBATCH --partition=SP2
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=8
#SBATCH -J lloyd_diamond_tax_NeuO_17.sh
#SBATCH --mem=24042
#SBATCH --time=172:00:00
#OpenMP settings:
export OMP_NUM_THREADS=1
export MKL_NUM_THREADS=1
export OMP_PLACES=threads
export OMP_PROC_BIND=spread
echo $SLURM_JOB_ID
echo $SLURM_SUBMIT_DIR
echo $SLURM_JOB_NODELIST

srun diamond blastp -q ../aligned_proteins/SRR5946905_NeuO_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5946905_NeuO_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5946906_NeuO_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5946906_NeuO_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5946907_NeuO_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5946907_NeuO_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5946908_NeuO_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5946908_NeuO_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5946909_NeuO_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5946909_NeuO_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5946910_NeuO_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5946910_NeuO_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5946911_NeuO_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5946911_NeuO_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5946912_NeuO_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5946912_NeuO_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5946913_NeuO_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5946913_NeuO_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5946914_NeuO_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5946914_NeuO_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5946915_NeuO_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5946915_NeuO_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5946916_NeuO_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5946916_NeuO_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5946917_NeuO_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5946917_NeuO_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5946918_NeuO_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5946918_NeuO_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5946919_NeuO_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5946919_NeuO_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5946920_NeuO_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5946920_NeuO_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5946921_NeuO_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5946921_NeuO_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5946922_NeuO_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5946922_NeuO_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5946923_NeuO_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5946923_NeuO_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5946924_NeuO_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5946924_NeuO_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5946925_NeuO_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5946925_NeuO_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5946926_NeuO_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5946926_NeuO_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5946927_NeuO_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5946927_NeuO_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5946928_NeuO_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5946928_NeuO_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5946929_NeuO_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5946929_NeuO_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5946930_NeuO_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5946930_NeuO_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5946931_NeuO_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5946931_NeuO_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5946932_NeuO_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5946932_NeuO_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5946933_NeuO_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5946933_NeuO_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5946934_NeuO_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5946934_NeuO_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5946935_NeuO_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5946935_NeuO_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5946936_NeuO_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5946936_NeuO_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5946937_NeuO_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5946937_NeuO_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5946938_NeuO_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5946938_NeuO_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5946939_NeuO_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5946939_NeuO_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5946940_NeuO_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5946940_NeuO_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5946941_NeuO_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5946941_NeuO_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5946942_NeuO_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5946942_NeuO_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5946943_NeuO_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5946943_NeuO_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5946944_NeuO_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5946944_NeuO_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5946945_NeuO_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5946945_NeuO_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5946946_NeuO_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5946946_NeuO_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5946947_NeuO_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5946947_NeuO_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5946948_NeuO_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5946948_NeuO_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5946949_NeuO_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5946949_NeuO_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5946950_NeuO_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5946950_NeuO_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5946951_NeuO_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5946951_NeuO_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5946952_NeuO_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5946952_NeuO_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5946953_NeuO_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5946953_NeuO_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5946954_NeuO_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5946954_NeuO_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
