#!/bin/bash
#SBATCH --partition=SP2
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=8
#SBATCH -J lloyd_diamond_tax_NeuB_4.sh
#SBATCH --mem=24042
#SBATCH --time=172:00:00
#OpenMP settings:
export OMP_NUM_THREADS=1
export MKL_NUM_THREADS=1
export OMP_PLACES=threads
export OMP_PROC_BIND=spread
echo $SLURM_JOB_ID
echo $SLURM_SUBMIT_DIR
echo $SLURM_JOB_NODELIST

srun diamond blastp -q ../aligned_proteins/SRR5935890_NeuB_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5935890_NeuB_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5935891_NeuB_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5935891_NeuB_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5935892_NeuB_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5935892_NeuB_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5935893_NeuB_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5935893_NeuB_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5935894_NeuB_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5935894_NeuB_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5935895_NeuB_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5935895_NeuB_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5935896_NeuB_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5935896_NeuB_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5935897_NeuB_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5935897_NeuB_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5935898_NeuB_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5935898_NeuB_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5935899_NeuB_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5935899_NeuB_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5935900_NeuB_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5935900_NeuB_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5935901_NeuB_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5935901_NeuB_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5935902_NeuB_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5935902_NeuB_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5935903_NeuB_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5935903_NeuB_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5935904_NeuB_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5935904_NeuB_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5935905_NeuB_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5935905_NeuB_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5935906_NeuB_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5935906_NeuB_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5935907_NeuB_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5935907_NeuB_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5935908_NeuB_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5935908_NeuB_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5935909_NeuB_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5935909_NeuB_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5935910_NeuB_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5935910_NeuB_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5935911_NeuB_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5935911_NeuB_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5935912_NeuB_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5935912_NeuB_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5935913_NeuB_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5935913_NeuB_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5935914_NeuB_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5935914_NeuB_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5935915_NeuB_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5935915_NeuB_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5935916_NeuB_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5935916_NeuB_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5935917_NeuB_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5935917_NeuB_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5935918_NeuB_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5935918_NeuB_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5935919_NeuB_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5935919_NeuB_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5935920_NeuB_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5935920_NeuB_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5935921_NeuB_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5935921_NeuB_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5935922_NeuB_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5935922_NeuB_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5935923_NeuB_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5935923_NeuB_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5935924_NeuB_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5935924_NeuB_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5935925_NeuB_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5935925_NeuB_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5935926_NeuB_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5935926_NeuB_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5935927_NeuB_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5935927_NeuB_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5935928_NeuB_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5935928_NeuB_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5935929_NeuB_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5935929_NeuB_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5935930_NeuB_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5935930_NeuB_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5935931_NeuB_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5935931_NeuB_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5935932_NeuB_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5935932_NeuB_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5935933_NeuB_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5935933_NeuB_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5935934_NeuB_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5935934_NeuB_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5935935_NeuB_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5935935_NeuB_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5935936_NeuB_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5935936_NeuB_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5935937_NeuB_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5935937_NeuB_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5935938_NeuB_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5935938_NeuB_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5935939_NeuB_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5935939_NeuB_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
