#!/bin/bash
#SBATCH --partition=SP2
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=8
#SBATCH -J lloyd_diamond_tax_Lic3A_19.sh
#SBATCH --mem=24042
#SBATCH --time=172:00:00
#OpenMP settings:
export OMP_NUM_THREADS=1
export MKL_NUM_THREADS=1
export OMP_PLACES=threads
export OMP_PROC_BIND=spread
echo $SLURM_JOB_ID
echo $SLURM_SUBMIT_DIR
echo $SLURM_JOB_NODELIST

srun diamond blastp -q ../aligned_proteins/SRR5947005_Lic3A_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5947005_Lic3A_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5947006_Lic3A_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5947006_Lic3A_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5947007_Lic3A_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5947007_Lic3A_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5947008_Lic3A_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5947008_Lic3A_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5947009_Lic3A_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5947009_Lic3A_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5947010_Lic3A_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5947010_Lic3A_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5947011_Lic3A_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5947011_Lic3A_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5947012_Lic3A_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5947012_Lic3A_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5947013_Lic3A_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5947013_Lic3A_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5947014_Lic3A_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5947014_Lic3A_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5947015_Lic3A_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5947015_Lic3A_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5947016_Lic3A_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5947016_Lic3A_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5947017_Lic3A_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5947017_Lic3A_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5947018_Lic3A_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5947018_Lic3A_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5947019_Lic3A_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5947019_Lic3A_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5947020_Lic3A_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5947020_Lic3A_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5947021_Lic3A_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5947021_Lic3A_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5947022_Lic3A_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5947022_Lic3A_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5947023_Lic3A_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5947023_Lic3A_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5947024_Lic3A_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5947024_Lic3A_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5947025_Lic3A_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5947025_Lic3A_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5947026_Lic3A_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5947026_Lic3A_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5947027_Lic3A_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5947027_Lic3A_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5947028_Lic3A_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5947028_Lic3A_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5947029_Lic3A_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5947029_Lic3A_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5947030_Lic3A_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5947030_Lic3A_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5947031_Lic3A_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5947031_Lic3A_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5947032_Lic3A_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5947032_Lic3A_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5947033_Lic3A_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5947033_Lic3A_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5947034_Lic3A_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5947034_Lic3A_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5947035_Lic3A_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5947035_Lic3A_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5947036_Lic3A_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5947036_Lic3A_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5947037_Lic3A_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5947037_Lic3A_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5947038_Lic3A_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5947038_Lic3A_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5947039_Lic3A_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5947039_Lic3A_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5947040_Lic3A_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5947040_Lic3A_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5947041_Lic3A_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5947041_Lic3A_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5947042_Lic3A_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5947042_Lic3A_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5947043_Lic3A_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5947043_Lic3A_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5947044_Lic3A_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5947044_Lic3A_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5947045_Lic3A_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5947045_Lic3A_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5947046_Lic3A_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5947046_Lic3A_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5947047_Lic3A_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5947047_Lic3A_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5947048_Lic3A_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5947048_Lic3A_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5947049_Lic3A_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5947049_Lic3A_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5947050_Lic3A_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5947050_Lic3A_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5947051_Lic3A_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5947051_Lic3A_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5947052_Lic3A_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5947052_Lic3A_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5947053_Lic3A_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5947053_Lic3A_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5947054_Lic3A_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5947054_Lic3A_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
