#!/bin/bash
#SBATCH --partition=SP2
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=8
#SBATCH -J lloyd_diamond_tax_NeuS_26.sh
#SBATCH --mem=24042
#SBATCH --time=172:00:00
#OpenMP settings:
export OMP_NUM_THREADS=1
export MKL_NUM_THREADS=1
export OMP_PLACES=threads
export OMP_PROC_BIND=spread
echo $SLURM_JOB_ID
echo $SLURM_SUBMIT_DIR
echo $SLURM_JOB_NODELIST

srun diamond blastp -q ../aligned_proteins/SRR5950734_NeuS_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5950734_NeuS_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5950735_NeuS_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5950735_NeuS_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5950736_NeuS_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5950736_NeuS_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5950737_NeuS_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5950737_NeuS_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5950738_NeuS_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5950738_NeuS_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5950739_NeuS_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5950739_NeuS_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5950740_NeuS_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5950740_NeuS_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5950741_NeuS_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5950741_NeuS_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5950742_NeuS_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5950742_NeuS_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5950743_NeuS_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5950743_NeuS_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5950744_NeuS_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5950744_NeuS_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5950745_NeuS_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5950745_NeuS_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5950746_NeuS_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5950746_NeuS_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5950747_NeuS_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5950747_NeuS_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5950748_NeuS_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5950748_NeuS_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5950749_NeuS_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5950749_NeuS_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5950750_NeuS_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5950750_NeuS_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5950751_NeuS_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5950751_NeuS_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5950752_NeuS_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5950752_NeuS_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5950753_NeuS_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5950753_NeuS_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5950754_NeuS_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5950754_NeuS_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5950755_NeuS_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5950755_NeuS_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5950756_NeuS_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5950756_NeuS_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5950757_NeuS_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5950757_NeuS_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5950758_NeuS_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5950758_NeuS_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5950759_NeuS_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5950759_NeuS_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5950760_NeuS_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5950760_NeuS_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5950761_NeuS_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5950761_NeuS_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5950762_NeuS_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5950762_NeuS_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5950763_NeuS_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5950763_NeuS_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5950764_NeuS_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5950764_NeuS_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5950765_NeuS_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5950765_NeuS_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5950766_NeuS_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5950766_NeuS_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5950767_NeuS_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5950767_NeuS_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5950768_NeuS_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5950768_NeuS_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5950769_NeuS_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5950769_NeuS_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5950770_NeuS_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5950770_NeuS_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5950771_NeuS_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5950771_NeuS_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5950772_NeuS_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5950772_NeuS_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5950773_NeuS_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5950773_NeuS_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5950774_NeuS_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5950774_NeuS_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5950775_NeuS_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5950775_NeuS_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5950776_NeuS_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5950776_NeuS_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5950777_NeuS_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5950777_NeuS_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5950778_NeuS_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5950778_NeuS_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5950779_NeuS_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5950779_NeuS_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5950780_NeuS_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5950780_NeuS_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5950781_NeuS_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5950781_NeuS_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5950782_NeuS_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5950782_NeuS_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5950783_NeuS_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5950783_NeuS_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
