#!/bin/bash
#SBATCH --partition=SP2
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=8
#SBATCH -J lloyd_diamond_tax_NeuO_9.sh
#SBATCH --mem=24042
#SBATCH --time=172:00:00
#OpenMP settings:
export OMP_NUM_THREADS=1
export MKL_NUM_THREADS=1
export OMP_PLACES=threads
export OMP_PROC_BIND=spread
echo $SLURM_JOB_ID
echo $SLURM_SUBMIT_DIR
echo $SLURM_JOB_NODELIST

srun diamond blastp -q ../aligned_proteins/SRR5936140_NeuO_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5936140_NeuO_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5936141_NeuO_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5936141_NeuO_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5936142_NeuO_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5936142_NeuO_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5936143_NeuO_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5936143_NeuO_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5936144_NeuO_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5936144_NeuO_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5936145_NeuO_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5936145_NeuO_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5936146_NeuO_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5936146_NeuO_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5936147_NeuO_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5936147_NeuO_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5936148_NeuO_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5936148_NeuO_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5936149_NeuO_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5936149_NeuO_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5936150_NeuO_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5936150_NeuO_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5936151_NeuO_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5936151_NeuO_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5936152_NeuO_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5936152_NeuO_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5936153_NeuO_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5936153_NeuO_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5936154_NeuO_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5936154_NeuO_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5936155_NeuO_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5936155_NeuO_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5936156_NeuO_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5936156_NeuO_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5936157_NeuO_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5936157_NeuO_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5936158_NeuO_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5936158_NeuO_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5936159_NeuO_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5936159_NeuO_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5936160_NeuO_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5936160_NeuO_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5936161_NeuO_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5936161_NeuO_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5936162_NeuO_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5936162_NeuO_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5936163_NeuO_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5936163_NeuO_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5936164_NeuO_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5936164_NeuO_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5936165_NeuO_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5936165_NeuO_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5936166_NeuO_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5936166_NeuO_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5936167_NeuO_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5936167_NeuO_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5936168_NeuO_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5936168_NeuO_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5936169_NeuO_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5936169_NeuO_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5936170_NeuO_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5936170_NeuO_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5936171_NeuO_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5936171_NeuO_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5936172_NeuO_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5936172_NeuO_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5936173_NeuO_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5936173_NeuO_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5936174_NeuO_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5936174_NeuO_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5936175_NeuO_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5936175_NeuO_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5936176_NeuO_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5936176_NeuO_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5936177_NeuO_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5936177_NeuO_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5936178_NeuO_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5936178_NeuO_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5936179_NeuO_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5936179_NeuO_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5936180_NeuO_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5936180_NeuO_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5936181_NeuO_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5936181_NeuO_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5936182_NeuO_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5936182_NeuO_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5936183_NeuO_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5936183_NeuO_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5936184_NeuO_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5936184_NeuO_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5936185_NeuO_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5936185_NeuO_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5936186_NeuO_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5936186_NeuO_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5936187_NeuO_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5936187_NeuO_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5936188_NeuO_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5936188_NeuO_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5936189_NeuO_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5936189_NeuO_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
