#!/bin/bash
#SBATCH --partition=SP2
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=8
#SBATCH -J lloyd_diamond_tax_KpsE_8.sh
#SBATCH --mem=24042
#SBATCH --time=172:00:00
#OpenMP settings:
export OMP_NUM_THREADS=1
export MKL_NUM_THREADS=1
export OMP_PLACES=threads
export OMP_PROC_BIND=spread
echo $SLURM_JOB_ID
echo $SLURM_SUBMIT_DIR
echo $SLURM_JOB_NODELIST

srun diamond blastp -q ../aligned_proteins/SRR5936090_KpsE_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5936090_KpsE_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5936091_KpsE_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5936091_KpsE_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5936092_KpsE_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5936092_KpsE_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5936093_KpsE_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5936093_KpsE_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5936094_KpsE_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5936094_KpsE_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5936095_KpsE_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5936095_KpsE_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5936096_KpsE_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5936096_KpsE_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5936097_KpsE_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5936097_KpsE_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5936098_KpsE_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5936098_KpsE_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5936099_KpsE_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5936099_KpsE_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5936100_KpsE_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5936100_KpsE_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5936101_KpsE_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5936101_KpsE_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5936102_KpsE_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5936102_KpsE_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5936103_KpsE_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5936103_KpsE_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5936104_KpsE_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5936104_KpsE_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5936105_KpsE_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5936105_KpsE_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5936106_KpsE_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5936106_KpsE_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5936107_KpsE_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5936107_KpsE_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5936108_KpsE_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5936108_KpsE_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5936109_KpsE_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5936109_KpsE_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5936110_KpsE_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5936110_KpsE_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5936111_KpsE_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5936111_KpsE_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5936112_KpsE_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5936112_KpsE_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5936113_KpsE_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5936113_KpsE_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5936114_KpsE_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5936114_KpsE_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5936115_KpsE_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5936115_KpsE_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5936116_KpsE_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5936116_KpsE_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5936117_KpsE_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5936117_KpsE_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5936118_KpsE_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5936118_KpsE_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5936119_KpsE_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5936119_KpsE_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5936120_KpsE_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5936120_KpsE_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5936121_KpsE_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5936121_KpsE_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5936122_KpsE_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5936122_KpsE_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5936123_KpsE_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5936123_KpsE_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5936124_KpsE_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5936124_KpsE_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5936125_KpsE_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5936125_KpsE_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5936126_KpsE_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5936126_KpsE_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5936127_KpsE_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5936127_KpsE_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5936128_KpsE_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5936128_KpsE_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5936129_KpsE_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5936129_KpsE_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5936130_KpsE_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5936130_KpsE_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5936131_KpsE_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5936131_KpsE_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5936132_KpsE_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5936132_KpsE_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5936133_KpsE_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5936133_KpsE_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5936134_KpsE_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5936134_KpsE_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5936135_KpsE_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5936135_KpsE_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5936136_KpsE_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5936136_KpsE_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5936137_KpsE_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5936137_KpsE_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5936138_KpsE_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5936138_KpsE_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5936139_KpsE_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5936139_KpsE_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
