#!/bin/bash
#SBATCH --partition=SP2
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=8
#SBATCH -J lloyd_diamond_tax_KpsE_25.sh
#SBATCH --mem=24042
#SBATCH --time=172:00:00
#OpenMP settings:
export OMP_NUM_THREADS=1
export MKL_NUM_THREADS=1
export OMP_PLACES=threads
export OMP_PROC_BIND=spread
echo $SLURM_JOB_ID
echo $SLURM_SUBMIT_DIR
echo $SLURM_JOB_NODELIST

srun diamond blastp -q ../aligned_proteins/SRR5950684_KpsE_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5950684_KpsE_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5950685_KpsE_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5950685_KpsE_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5950686_KpsE_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5950686_KpsE_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5950687_KpsE_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5950687_KpsE_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5950688_KpsE_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5950688_KpsE_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5950689_KpsE_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5950689_KpsE_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5950690_KpsE_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5950690_KpsE_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5950691_KpsE_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5950691_KpsE_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5950692_KpsE_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5950692_KpsE_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5950693_KpsE_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5950693_KpsE_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5950694_KpsE_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5950694_KpsE_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5950695_KpsE_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5950695_KpsE_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5950696_KpsE_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5950696_KpsE_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5950697_KpsE_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5950697_KpsE_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5950698_KpsE_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5950698_KpsE_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5950699_KpsE_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5950699_KpsE_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5950700_KpsE_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5950700_KpsE_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5950701_KpsE_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5950701_KpsE_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5950702_KpsE_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5950702_KpsE_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5950703_KpsE_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5950703_KpsE_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5950704_KpsE_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5950704_KpsE_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5950705_KpsE_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5950705_KpsE_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5950706_KpsE_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5950706_KpsE_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5950707_KpsE_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5950707_KpsE_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5950708_KpsE_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5950708_KpsE_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5950709_KpsE_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5950709_KpsE_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5950710_KpsE_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5950710_KpsE_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5950711_KpsE_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5950711_KpsE_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5950712_KpsE_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5950712_KpsE_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5950713_KpsE_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5950713_KpsE_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5950714_KpsE_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5950714_KpsE_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5950715_KpsE_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5950715_KpsE_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5950716_KpsE_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5950716_KpsE_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5950717_KpsE_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5950717_KpsE_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5950718_KpsE_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5950718_KpsE_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5950719_KpsE_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5950719_KpsE_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5950720_KpsE_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5950720_KpsE_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5950721_KpsE_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5950721_KpsE_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5950722_KpsE_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5950722_KpsE_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5950723_KpsE_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5950723_KpsE_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5950724_KpsE_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5950724_KpsE_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5950725_KpsE_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5950725_KpsE_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5950726_KpsE_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5950726_KpsE_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5950727_KpsE_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5950727_KpsE_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5950728_KpsE_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5950728_KpsE_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5950729_KpsE_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5950729_KpsE_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5950730_KpsE_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5950730_KpsE_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5950731_KpsE_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5950731_KpsE_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5950732_KpsE_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5950732_KpsE_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5950733_KpsE_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5950733_KpsE_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
