#!/bin/bash
#SBATCH --partition=SP2
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=8
#SBATCH -J lloyd_diamond_tax_NeuO_11.sh
#SBATCH --mem=24042
#SBATCH --time=172:00:00
#OpenMP settings:
export OMP_NUM_THREADS=1
export MKL_NUM_THREADS=1
export OMP_PLACES=threads
export OMP_PROC_BIND=spread
echo $SLURM_JOB_ID
echo $SLURM_SUBMIT_DIR
echo $SLURM_JOB_NODELIST

srun diamond blastp -q ../aligned_proteins/SRR5946605_NeuO_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5946605_NeuO_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5946606_NeuO_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5946606_NeuO_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5946607_NeuO_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5946607_NeuO_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5946608_NeuO_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5946608_NeuO_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5946609_NeuO_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5946609_NeuO_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5946610_NeuO_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5946610_NeuO_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5946611_NeuO_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5946611_NeuO_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5946612_NeuO_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5946612_NeuO_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5946613_NeuO_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5946613_NeuO_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5946614_NeuO_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5946614_NeuO_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5946615_NeuO_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5946615_NeuO_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5946616_NeuO_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5946616_NeuO_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5946617_NeuO_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5946617_NeuO_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5946618_NeuO_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5946618_NeuO_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5946619_NeuO_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5946619_NeuO_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5946620_NeuO_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5946620_NeuO_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5946621_NeuO_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5946621_NeuO_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5946622_NeuO_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5946622_NeuO_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5946623_NeuO_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5946623_NeuO_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5946624_NeuO_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5946624_NeuO_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5946625_NeuO_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5946625_NeuO_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5946626_NeuO_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5946626_NeuO_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5946627_NeuO_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5946627_NeuO_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5946628_NeuO_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5946628_NeuO_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5946629_NeuO_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5946629_NeuO_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5946630_NeuO_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5946630_NeuO_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5946631_NeuO_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5946631_NeuO_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5946632_NeuO_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5946632_NeuO_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5946633_NeuO_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5946633_NeuO_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5946634_NeuO_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5946634_NeuO_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5946635_NeuO_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5946635_NeuO_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5946636_NeuO_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5946636_NeuO_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5946637_NeuO_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5946637_NeuO_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5946638_NeuO_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5946638_NeuO_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5946639_NeuO_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5946639_NeuO_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5946640_NeuO_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5946640_NeuO_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5946641_NeuO_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5946641_NeuO_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5946642_NeuO_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5946642_NeuO_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5946643_NeuO_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5946643_NeuO_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5946644_NeuO_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5946644_NeuO_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5946645_NeuO_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5946645_NeuO_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5946646_NeuO_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5946646_NeuO_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5946647_NeuO_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5946647_NeuO_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5946648_NeuO_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5946648_NeuO_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5946649_NeuO_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5946649_NeuO_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5946650_NeuO_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5946650_NeuO_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5946651_NeuO_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5946651_NeuO_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5946652_NeuO_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5946652_NeuO_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5946653_NeuO_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5946653_NeuO_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5946654_NeuO_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5946654_NeuO_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
