#!/bin/bash
#SBATCH --partition=SP2
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=8
#SBATCH -J lloyd_diamond_tax_NeuA_1.sh
#SBATCH --mem=24042
#SBATCH --time=172:00:00
#OpenMP settings:
export OMP_NUM_THREADS=1
export MKL_NUM_THREADS=1
export OMP_PLACES=threads
export OMP_PROC_BIND=spread
echo $SLURM_JOB_ID
echo $SLURM_SUBMIT_DIR
echo $SLURM_JOB_NODELIST

srun diamond blastp -q ../aligned_proteins/SRR5983412_NeuA_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5983412_NeuA_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5947833_NeuA_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5947833_NeuA_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5983391_NeuA_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5983391_NeuA_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5983393_NeuA_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5983393_NeuA_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5947823_NeuA_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5947823_NeuA_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5947868_NeuA_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5947868_NeuA_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5983308_NeuA_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5983308_NeuA_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5947839_NeuA_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5947839_NeuA_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5983472_NeuA_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5983472_NeuA_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5983469_NeuA_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5983469_NeuA_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5983448_NeuA_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5983448_NeuA_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5983279_NeuA_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5983279_NeuA_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5983275_NeuA_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5983275_NeuA_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5983446_NeuA_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5983446_NeuA_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5983422_NeuA_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5983422_NeuA_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5983441_NeuA_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5983441_NeuA_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5983386_NeuA_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5983386_NeuA_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5983459_NeuA_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5983459_NeuA_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5983360_NeuA_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5983360_NeuA_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5983377_NeuA_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5983377_NeuA_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5983367_NeuA_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5983367_NeuA_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5983365_NeuA_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5983365_NeuA_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5983283_NeuA_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5983283_NeuA_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5983289_NeuA_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5983289_NeuA_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5983294_NeuA_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5983294_NeuA_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5983264_NeuA_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5983264_NeuA_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5947815_NeuA_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5947815_NeuA_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5947832_NeuA_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5947832_NeuA_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5983418_NeuA_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5983418_NeuA_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5947825_NeuA_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5947825_NeuA_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5947858_NeuA_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5947858_NeuA_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5983342_NeuA_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5983342_NeuA_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5983272_NeuA_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5983272_NeuA_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5983427_NeuA_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5983427_NeuA_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5983326_NeuA_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5983326_NeuA_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5983314_NeuA_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5983314_NeuA_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5947819_NeuA_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5947819_NeuA_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5947827_NeuA_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5947827_NeuA_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5947843_NeuA_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5947843_NeuA_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5983346_NeuA_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5983346_NeuA_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5947850_NeuA_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5947850_NeuA_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5947851_NeuA_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5947851_NeuA_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5947883_NeuA_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5947883_NeuA_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5983304_NeuA_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5983304_NeuA_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5983462_NeuA_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5983462_NeuA_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5983280_NeuA_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5983280_NeuA_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5983470_NeuA_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5983470_NeuA_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5983480_NeuA_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5983480_NeuA_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5983484_NeuA_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5983484_NeuA_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5983273_NeuA_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5983273_NeuA_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5983423_NeuA_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5983423_NeuA_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5983438_NeuA_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5983438_NeuA_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5983372_NeuA_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5983372_NeuA_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5983400_NeuA_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5983400_NeuA_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5983331_NeuA_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5983331_NeuA_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5983325_NeuA_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5983325_NeuA_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5983355_NeuA_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5983355_NeuA_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5983284_NeuA_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5983284_NeuA_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5983291_NeuA_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5983291_NeuA_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5983411_NeuA_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5983411_NeuA_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5947813_NeuA_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5947813_NeuA_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5947809_NeuA_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5947809_NeuA_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5947818_NeuA_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5947818_NeuA_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5947816_NeuA_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5947816_NeuA_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5947837_NeuA_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5947837_NeuA_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5947831_NeuA_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5947831_NeuA_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5983479_NeuA_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5983479_NeuA_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5947822_NeuA_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5947822_NeuA_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5983481_NeuA_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5983481_NeuA_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5983276_NeuA_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5983276_NeuA_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5983428_NeuA_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5983428_NeuA_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5983382_NeuA_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5983382_NeuA_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5983376_NeuA_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5983376_NeuA_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5983403_NeuA_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5983403_NeuA_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5983299_NeuA_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5983299_NeuA_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5983357_NeuA_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5983357_NeuA_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5983297_NeuA_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5983297_NeuA_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5983267_NeuA_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5983267_NeuA_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5983301_NeuA_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5983301_NeuA_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5983282_NeuA_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5983282_NeuA_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5983474_NeuA_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5983474_NeuA_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5983292_NeuA_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5983292_NeuA_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5983450_NeuA_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5983450_NeuA_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5983268_NeuA_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5983268_NeuA_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5983434_NeuA_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5983434_NeuA_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5983384_NeuA_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5983384_NeuA_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5983431_NeuA_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5983431_NeuA_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5983405_NeuA_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5983405_NeuA_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5983329_NeuA_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5983329_NeuA_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5983296_NeuA_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5983296_NeuA_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
