#!/bin/bash
#SBATCH --partition=SP2
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=8
#SBATCH -J lloyd_diamond_tax_extra_SiaM_22.sh
#SBATCH --mem=24042
#SBATCH --time=172:00:00
#OpenMP settings:
export OMP_NUM_THREADS=1
export MKL_NUM_THREADS=1
export OMP_PLACES=threads
export OMP_PROC_BIND=spread
echo $SLURM_JOB_ID
echo $SLURM_SUBMIT_DIR
echo $SLURM_JOB_NODELIST

srun diamond blastp -q ../aligned_proteins_extra/SRR5950534_SiaM_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5950534_SiaM_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins_extra/SRR5950535_SiaM_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5950535_SiaM_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins_extra/SRR5950536_SiaM_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5950536_SiaM_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins_extra/SRR5950537_SiaM_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5950537_SiaM_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins_extra/SRR5950538_SiaM_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5950538_SiaM_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins_extra/SRR5950539_SiaM_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5950539_SiaM_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins_extra/SRR5950540_SiaM_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5950540_SiaM_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins_extra/SRR5950541_SiaM_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5950541_SiaM_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins_extra/SRR5950542_SiaM_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5950542_SiaM_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins_extra/SRR5950543_SiaM_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5950543_SiaM_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins_extra/SRR5950544_SiaM_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5950544_SiaM_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins_extra/SRR5950545_SiaM_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5950545_SiaM_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins_extra/SRR5950546_SiaM_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5950546_SiaM_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins_extra/SRR5950547_SiaM_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5950547_SiaM_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins_extra/SRR5950548_SiaM_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5950548_SiaM_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins_extra/SRR5950549_SiaM_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5950549_SiaM_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins_extra/SRR5950550_SiaM_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5950550_SiaM_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins_extra/SRR5950551_SiaM_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5950551_SiaM_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins_extra/SRR5950552_SiaM_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5950552_SiaM_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins_extra/SRR5950553_SiaM_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5950553_SiaM_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins_extra/SRR5950554_SiaM_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5950554_SiaM_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins_extra/SRR5950555_SiaM_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5950555_SiaM_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins_extra/SRR5950556_SiaM_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5950556_SiaM_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins_extra/SRR5950557_SiaM_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5950557_SiaM_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins_extra/SRR5950558_SiaM_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5950558_SiaM_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins_extra/SRR5950559_SiaM_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5950559_SiaM_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins_extra/SRR5950560_SiaM_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5950560_SiaM_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins_extra/SRR5950561_SiaM_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5950561_SiaM_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins_extra/SRR5950562_SiaM_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5950562_SiaM_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins_extra/SRR5950563_SiaM_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5950563_SiaM_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins_extra/SRR5950564_SiaM_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5950564_SiaM_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins_extra/SRR5950565_SiaM_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5950565_SiaM_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins_extra/SRR5950566_SiaM_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5950566_SiaM_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins_extra/SRR5950567_SiaM_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5950567_SiaM_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins_extra/SRR5950568_SiaM_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5950568_SiaM_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins_extra/SRR5950569_SiaM_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5950569_SiaM_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins_extra/SRR5950570_SiaM_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5950570_SiaM_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins_extra/SRR5950571_SiaM_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5950571_SiaM_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins_extra/SRR5950572_SiaM_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5950572_SiaM_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins_extra/SRR5950573_SiaM_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5950573_SiaM_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins_extra/SRR5950574_SiaM_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5950574_SiaM_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins_extra/SRR5950575_SiaM_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5950575_SiaM_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins_extra/SRR5950576_SiaM_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5950576_SiaM_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins_extra/SRR5950577_SiaM_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5950577_SiaM_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins_extra/SRR5950578_SiaM_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5950578_SiaM_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins_extra/SRR5950579_SiaM_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5950579_SiaM_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins_extra/SRR5950580_SiaM_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5950580_SiaM_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins_extra/SRR5950581_SiaM_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5950581_SiaM_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins_extra/SRR5950582_SiaM_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5950582_SiaM_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins_extra/SRR5950583_SiaM_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5950583_SiaM_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
