#!/bin/bash
#SBATCH --partition=SP2
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=8
#SBATCH -J lloyd_diamond_tax_extra_NanT_22.sh
#SBATCH --mem=24042
#SBATCH --time=172:00:00
#OpenMP settings:
export OMP_NUM_THREADS=1
export MKL_NUM_THREADS=1
export OMP_PLACES=threads
export OMP_PROC_BIND=spread
echo $SLURM_JOB_ID
echo $SLURM_SUBMIT_DIR
echo $SLURM_JOB_NODELIST

srun diamond blastp -q ../aligned_proteins_extra/SRR5950534_NanT_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5950534_NanT_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins_extra/SRR5950535_NanT_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5950535_NanT_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins_extra/SRR5950536_NanT_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5950536_NanT_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins_extra/SRR5950537_NanT_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5950537_NanT_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins_extra/SRR5950538_NanT_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5950538_NanT_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins_extra/SRR5950539_NanT_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5950539_NanT_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins_extra/SRR5950540_NanT_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5950540_NanT_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins_extra/SRR5950541_NanT_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5950541_NanT_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins_extra/SRR5950542_NanT_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5950542_NanT_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins_extra/SRR5950543_NanT_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5950543_NanT_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins_extra/SRR5950544_NanT_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5950544_NanT_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins_extra/SRR5950545_NanT_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5950545_NanT_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins_extra/SRR5950546_NanT_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5950546_NanT_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins_extra/SRR5950547_NanT_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5950547_NanT_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins_extra/SRR5950548_NanT_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5950548_NanT_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins_extra/SRR5950549_NanT_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5950549_NanT_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins_extra/SRR5950550_NanT_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5950550_NanT_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins_extra/SRR5950551_NanT_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5950551_NanT_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins_extra/SRR5950552_NanT_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5950552_NanT_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins_extra/SRR5950553_NanT_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5950553_NanT_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins_extra/SRR5950554_NanT_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5950554_NanT_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins_extra/SRR5950555_NanT_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5950555_NanT_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins_extra/SRR5950556_NanT_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5950556_NanT_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins_extra/SRR5950557_NanT_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5950557_NanT_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins_extra/SRR5950558_NanT_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5950558_NanT_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins_extra/SRR5950559_NanT_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5950559_NanT_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins_extra/SRR5950560_NanT_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5950560_NanT_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins_extra/SRR5950561_NanT_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5950561_NanT_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins_extra/SRR5950562_NanT_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5950562_NanT_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins_extra/SRR5950563_NanT_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5950563_NanT_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins_extra/SRR5950564_NanT_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5950564_NanT_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins_extra/SRR5950565_NanT_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5950565_NanT_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins_extra/SRR5950566_NanT_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5950566_NanT_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins_extra/SRR5950567_NanT_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5950567_NanT_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins_extra/SRR5950568_NanT_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5950568_NanT_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins_extra/SRR5950569_NanT_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5950569_NanT_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins_extra/SRR5950570_NanT_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5950570_NanT_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins_extra/SRR5950571_NanT_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5950571_NanT_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins_extra/SRR5950572_NanT_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5950572_NanT_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins_extra/SRR5950573_NanT_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5950573_NanT_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins_extra/SRR5950574_NanT_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5950574_NanT_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins_extra/SRR5950575_NanT_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5950575_NanT_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins_extra/SRR5950576_NanT_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5950576_NanT_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins_extra/SRR5950577_NanT_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5950577_NanT_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins_extra/SRR5950578_NanT_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5950578_NanT_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins_extra/SRR5950579_NanT_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5950579_NanT_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins_extra/SRR5950580_NanT_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5950580_NanT_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins_extra/SRR5950581_NanT_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5950581_NanT_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins_extra/SRR5950582_NanT_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5950582_NanT_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins_extra/SRR5950583_NanT_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5950583_NanT_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
