#!/bin/bash
#SBATCH --partition=SP2
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=8
#SBATCH -J lloyd_diamond_tax_extra_SiaM_20.sh
#SBATCH --mem=24042
#SBATCH --time=172:00:00
#OpenMP settings:
export OMP_NUM_THREADS=1
export MKL_NUM_THREADS=1
export OMP_PLACES=threads
export OMP_PROC_BIND=spread
echo $SLURM_JOB_ID
echo $SLURM_SUBMIT_DIR
echo $SLURM_JOB_NODELIST

srun diamond blastp -q ../aligned_proteins/SRR5947055_SiaM_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5947055_SiaM_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5947056_SiaM_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5947056_SiaM_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5947057_SiaM_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5947057_SiaM_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5947058_SiaM_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5947058_SiaM_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5947059_SiaM_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5947059_SiaM_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5947060_SiaM_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5947060_SiaM_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5947061_SiaM_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5947061_SiaM_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5947062_SiaM_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5947062_SiaM_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5947063_SiaM_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5947063_SiaM_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5947064_SiaM_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5947064_SiaM_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5947065_SiaM_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5947065_SiaM_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5947066_SiaM_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5947066_SiaM_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5947067_SiaM_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5947067_SiaM_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5947068_SiaM_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5947068_SiaM_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5947069_SiaM_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5947069_SiaM_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5947070_SiaM_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5947070_SiaM_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5947071_SiaM_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5947071_SiaM_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5947072_SiaM_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5947072_SiaM_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5947073_SiaM_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5947073_SiaM_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5947074_SiaM_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5947074_SiaM_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5947075_SiaM_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5947075_SiaM_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5947076_SiaM_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5947076_SiaM_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5947077_SiaM_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5947077_SiaM_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5947078_SiaM_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5947078_SiaM_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5947079_SiaM_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5947079_SiaM_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5947080_SiaM_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5947080_SiaM_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5947081_SiaM_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5947081_SiaM_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5947082_SiaM_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5947082_SiaM_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5947083_SiaM_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5947083_SiaM_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5947084_SiaM_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5947084_SiaM_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5947085_SiaM_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5947085_SiaM_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5947086_SiaM_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5947086_SiaM_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5947087_SiaM_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5947087_SiaM_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5947088_SiaM_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5947088_SiaM_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5947089_SiaM_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5947089_SiaM_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5947090_SiaM_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5947090_SiaM_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5947091_SiaM_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5947091_SiaM_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5947092_SiaM_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5947092_SiaM_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5947093_SiaM_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5947093_SiaM_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5947094_SiaM_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5947094_SiaM_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5947095_SiaM_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5947095_SiaM_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5947096_SiaM_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5947096_SiaM_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5947097_SiaM_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5947097_SiaM_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5947098_SiaM_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5947098_SiaM_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5947099_SiaM_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5947099_SiaM_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5947100_SiaM_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5947100_SiaM_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5947101_SiaM_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5947101_SiaM_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5947102_SiaM_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5947102_SiaM_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5947103_SiaM_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5947103_SiaM_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5947104_SiaM_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5947104_SiaM_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
