#!/bin/bash
#SBATCH --partition=SP2
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=8
#SBATCH -J lloyd_diamond_tax_extra_NanA_SP_26.sh
#SBATCH --mem=24042
#SBATCH --time=172:00:00
#OpenMP settings:
export OMP_NUM_THREADS=1
export MKL_NUM_THREADS=1
export OMP_PLACES=threads
export OMP_PROC_BIND=spread
echo $SLURM_JOB_ID
echo $SLURM_SUBMIT_DIR
echo $SLURM_JOB_NODELIST

srun diamond blastp -q ../aligned_proteins/SRR5950734_NanA_SP_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5950734_NanA_SP_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5950735_NanA_SP_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5950735_NanA_SP_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5950736_NanA_SP_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5950736_NanA_SP_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5950737_NanA_SP_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5950737_NanA_SP_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5950738_NanA_SP_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5950738_NanA_SP_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5950739_NanA_SP_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5950739_NanA_SP_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5950740_NanA_SP_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5950740_NanA_SP_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5950741_NanA_SP_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5950741_NanA_SP_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5950742_NanA_SP_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5950742_NanA_SP_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5950743_NanA_SP_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5950743_NanA_SP_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5950744_NanA_SP_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5950744_NanA_SP_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5950745_NanA_SP_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5950745_NanA_SP_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5950746_NanA_SP_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5950746_NanA_SP_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5950747_NanA_SP_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5950747_NanA_SP_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5950748_NanA_SP_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5950748_NanA_SP_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5950749_NanA_SP_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5950749_NanA_SP_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5950750_NanA_SP_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5950750_NanA_SP_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5950751_NanA_SP_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5950751_NanA_SP_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5950752_NanA_SP_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5950752_NanA_SP_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5950753_NanA_SP_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5950753_NanA_SP_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5950754_NanA_SP_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5950754_NanA_SP_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5950755_NanA_SP_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5950755_NanA_SP_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5950756_NanA_SP_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5950756_NanA_SP_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5950757_NanA_SP_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5950757_NanA_SP_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5950758_NanA_SP_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5950758_NanA_SP_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5950759_NanA_SP_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5950759_NanA_SP_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5950760_NanA_SP_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5950760_NanA_SP_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5950761_NanA_SP_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5950761_NanA_SP_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5950762_NanA_SP_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5950762_NanA_SP_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5950763_NanA_SP_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5950763_NanA_SP_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5950764_NanA_SP_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5950764_NanA_SP_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5950765_NanA_SP_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5950765_NanA_SP_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5950766_NanA_SP_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5950766_NanA_SP_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5950767_NanA_SP_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5950767_NanA_SP_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5950768_NanA_SP_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5950768_NanA_SP_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5950769_NanA_SP_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5950769_NanA_SP_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5950770_NanA_SP_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5950770_NanA_SP_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5950771_NanA_SP_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5950771_NanA_SP_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5950772_NanA_SP_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5950772_NanA_SP_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5950773_NanA_SP_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5950773_NanA_SP_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5950774_NanA_SP_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5950774_NanA_SP_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5950775_NanA_SP_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5950775_NanA_SP_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5950776_NanA_SP_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5950776_NanA_SP_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5950777_NanA_SP_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5950777_NanA_SP_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5950778_NanA_SP_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5950778_NanA_SP_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5950779_NanA_SP_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5950779_NanA_SP_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5950780_NanA_SP_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5950780_NanA_SP_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5950781_NanA_SP_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5950781_NanA_SP_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5950782_NanA_SP_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5950782_NanA_SP_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5950783_NanA_SP_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5950783_NanA_SP_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
