#!/bin/bash
#SBATCH --partition=SP2
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=8
#SBATCH -J lloyd_diamond_tax_extra_NanA_SP_6.sh
#SBATCH --mem=24042
#SBATCH --time=172:00:00
#OpenMP settings:
export OMP_NUM_THREADS=1
export MKL_NUM_THREADS=1
export OMP_PLACES=threads
export OMP_PROC_BIND=spread
echo $SLURM_JOB_ID
echo $SLURM_SUBMIT_DIR
echo $SLURM_JOB_NODELIST

srun diamond blastp -q ../aligned_proteins/SRR5935990_NanA_SP_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5935990_NanA_SP_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5935991_NanA_SP_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5935991_NanA_SP_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5935992_NanA_SP_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5935992_NanA_SP_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5935993_NanA_SP_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5935993_NanA_SP_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5935994_NanA_SP_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5935994_NanA_SP_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5935995_NanA_SP_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5935995_NanA_SP_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5935996_NanA_SP_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5935996_NanA_SP_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5935997_NanA_SP_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5935997_NanA_SP_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5935998_NanA_SP_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5935998_NanA_SP_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5935999_NanA_SP_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5935999_NanA_SP_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5936000_NanA_SP_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5936000_NanA_SP_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5936001_NanA_SP_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5936001_NanA_SP_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5936002_NanA_SP_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5936002_NanA_SP_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5936003_NanA_SP_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5936003_NanA_SP_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5936004_NanA_SP_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5936004_NanA_SP_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5936005_NanA_SP_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5936005_NanA_SP_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5936006_NanA_SP_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5936006_NanA_SP_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5936007_NanA_SP_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5936007_NanA_SP_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5936008_NanA_SP_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5936008_NanA_SP_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5936009_NanA_SP_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5936009_NanA_SP_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5936010_NanA_SP_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5936010_NanA_SP_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5936011_NanA_SP_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5936011_NanA_SP_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5936012_NanA_SP_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5936012_NanA_SP_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5936013_NanA_SP_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5936013_NanA_SP_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5936014_NanA_SP_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5936014_NanA_SP_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5936015_NanA_SP_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5936015_NanA_SP_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5936016_NanA_SP_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5936016_NanA_SP_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5936017_NanA_SP_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5936017_NanA_SP_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5936018_NanA_SP_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5936018_NanA_SP_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5936019_NanA_SP_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5936019_NanA_SP_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5936020_NanA_SP_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5936020_NanA_SP_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5936021_NanA_SP_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5936021_NanA_SP_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5936022_NanA_SP_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5936022_NanA_SP_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5936023_NanA_SP_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5936023_NanA_SP_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5936024_NanA_SP_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5936024_NanA_SP_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5936025_NanA_SP_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5936025_NanA_SP_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5936026_NanA_SP_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5936026_NanA_SP_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5936027_NanA_SP_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5936027_NanA_SP_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5936028_NanA_SP_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5936028_NanA_SP_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5936029_NanA_SP_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5936029_NanA_SP_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5936030_NanA_SP_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5936030_NanA_SP_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5936031_NanA_SP_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5936031_NanA_SP_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5936032_NanA_SP_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5936032_NanA_SP_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5936033_NanA_SP_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5936033_NanA_SP_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5936034_NanA_SP_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5936034_NanA_SP_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5936035_NanA_SP_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5936035_NanA_SP_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5936036_NanA_SP_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5936036_NanA_SP_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5936037_NanA_SP_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5936037_NanA_SP_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5936038_NanA_SP_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5936038_NanA_SP_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5936039_NanA_SP_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5936039_NanA_SP_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
