#!/bin/bash
#SBATCH --partition=SP2
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=8
#SBATCH -J lloyd_diamond_tax_extra_NanB_PM_20.sh
#SBATCH --mem=24042
#SBATCH --time=172:00:00
#OpenMP settings:
export OMP_NUM_THREADS=1
export MKL_NUM_THREADS=1
export OMP_PLACES=threads
export OMP_PROC_BIND=spread
echo $SLURM_JOB_ID
echo $SLURM_SUBMIT_DIR
echo $SLURM_JOB_NODELIST

srun diamond blastp -q ../aligned_proteins_extra/SRR5947055_NanB_PM_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5947055_NanB_PM_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins_extra/SRR5947056_NanB_PM_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5947056_NanB_PM_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins_extra/SRR5947057_NanB_PM_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5947057_NanB_PM_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins_extra/SRR5947058_NanB_PM_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5947058_NanB_PM_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins_extra/SRR5947059_NanB_PM_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5947059_NanB_PM_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins_extra/SRR5947060_NanB_PM_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5947060_NanB_PM_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins_extra/SRR5947061_NanB_PM_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5947061_NanB_PM_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins_extra/SRR5947062_NanB_PM_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5947062_NanB_PM_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins_extra/SRR5947063_NanB_PM_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5947063_NanB_PM_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins_extra/SRR5947064_NanB_PM_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5947064_NanB_PM_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins_extra/SRR5947065_NanB_PM_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5947065_NanB_PM_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins_extra/SRR5947066_NanB_PM_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5947066_NanB_PM_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins_extra/SRR5947067_NanB_PM_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5947067_NanB_PM_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins_extra/SRR5947068_NanB_PM_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5947068_NanB_PM_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins_extra/SRR5947069_NanB_PM_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5947069_NanB_PM_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins_extra/SRR5947070_NanB_PM_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5947070_NanB_PM_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins_extra/SRR5947071_NanB_PM_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5947071_NanB_PM_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins_extra/SRR5947072_NanB_PM_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5947072_NanB_PM_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins_extra/SRR5947073_NanB_PM_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5947073_NanB_PM_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins_extra/SRR5947074_NanB_PM_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5947074_NanB_PM_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins_extra/SRR5947075_NanB_PM_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5947075_NanB_PM_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins_extra/SRR5947076_NanB_PM_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5947076_NanB_PM_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins_extra/SRR5947077_NanB_PM_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5947077_NanB_PM_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins_extra/SRR5947078_NanB_PM_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5947078_NanB_PM_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins_extra/SRR5947079_NanB_PM_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5947079_NanB_PM_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins_extra/SRR5947080_NanB_PM_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5947080_NanB_PM_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins_extra/SRR5947081_NanB_PM_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5947081_NanB_PM_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins_extra/SRR5947082_NanB_PM_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5947082_NanB_PM_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins_extra/SRR5947083_NanB_PM_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5947083_NanB_PM_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins_extra/SRR5947084_NanB_PM_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5947084_NanB_PM_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins_extra/SRR5947085_NanB_PM_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5947085_NanB_PM_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins_extra/SRR5947086_NanB_PM_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5947086_NanB_PM_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins_extra/SRR5947087_NanB_PM_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5947087_NanB_PM_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins_extra/SRR5947088_NanB_PM_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5947088_NanB_PM_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins_extra/SRR5947089_NanB_PM_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5947089_NanB_PM_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins_extra/SRR5947090_NanB_PM_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5947090_NanB_PM_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins_extra/SRR5947091_NanB_PM_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5947091_NanB_PM_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins_extra/SRR5947092_NanB_PM_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5947092_NanB_PM_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins_extra/SRR5947093_NanB_PM_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5947093_NanB_PM_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins_extra/SRR5947094_NanB_PM_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5947094_NanB_PM_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins_extra/SRR5947095_NanB_PM_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5947095_NanB_PM_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins_extra/SRR5947096_NanB_PM_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5947096_NanB_PM_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins_extra/SRR5947097_NanB_PM_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5947097_NanB_PM_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins_extra/SRR5947098_NanB_PM_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5947098_NanB_PM_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins_extra/SRR5947099_NanB_PM_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5947099_NanB_PM_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins_extra/SRR5947100_NanB_PM_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5947100_NanB_PM_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins_extra/SRR5947101_NanB_PM_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5947101_NanB_PM_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins_extra/SRR5947102_NanB_PM_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5947102_NanB_PM_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins_extra/SRR5947103_NanB_PM_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5947103_NanB_PM_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins_extra/SRR5947104_NanB_PM_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5947104_NanB_PM_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
