#!/bin/bash
#SBATCH --partition=SP2
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=8
#SBATCH -J lloyd_diamond_tax_extra_NanH_8.sh
#SBATCH --mem=24042
#SBATCH --time=172:00:00
#OpenMP settings:
export OMP_NUM_THREADS=1
export MKL_NUM_THREADS=1
export OMP_PLACES=threads
export OMP_PROC_BIND=spread
echo $SLURM_JOB_ID
echo $SLURM_SUBMIT_DIR
echo $SLURM_JOB_NODELIST

srun diamond blastp -q ../aligned_proteins_extra/SRR5936090_NanH_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5936090_NanH_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins_extra/SRR5936091_NanH_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5936091_NanH_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins_extra/SRR5936092_NanH_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5936092_NanH_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins_extra/SRR5936093_NanH_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5936093_NanH_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins_extra/SRR5936094_NanH_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5936094_NanH_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins_extra/SRR5936095_NanH_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5936095_NanH_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins_extra/SRR5936096_NanH_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5936096_NanH_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins_extra/SRR5936097_NanH_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5936097_NanH_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins_extra/SRR5936098_NanH_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5936098_NanH_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins_extra/SRR5936099_NanH_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5936099_NanH_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins_extra/SRR5936100_NanH_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5936100_NanH_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins_extra/SRR5936101_NanH_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5936101_NanH_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins_extra/SRR5936102_NanH_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5936102_NanH_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins_extra/SRR5936103_NanH_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5936103_NanH_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins_extra/SRR5936104_NanH_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5936104_NanH_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins_extra/SRR5936105_NanH_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5936105_NanH_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins_extra/SRR5936106_NanH_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5936106_NanH_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins_extra/SRR5936107_NanH_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5936107_NanH_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins_extra/SRR5936108_NanH_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5936108_NanH_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins_extra/SRR5936109_NanH_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5936109_NanH_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins_extra/SRR5936110_NanH_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5936110_NanH_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins_extra/SRR5936111_NanH_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5936111_NanH_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins_extra/SRR5936112_NanH_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5936112_NanH_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins_extra/SRR5936113_NanH_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5936113_NanH_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins_extra/SRR5936114_NanH_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5936114_NanH_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins_extra/SRR5936115_NanH_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5936115_NanH_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins_extra/SRR5936116_NanH_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5936116_NanH_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins_extra/SRR5936117_NanH_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5936117_NanH_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins_extra/SRR5936118_NanH_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5936118_NanH_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins_extra/SRR5936119_NanH_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5936119_NanH_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins_extra/SRR5936120_NanH_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5936120_NanH_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins_extra/SRR5936121_NanH_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5936121_NanH_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins_extra/SRR5936122_NanH_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5936122_NanH_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins_extra/SRR5936123_NanH_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5936123_NanH_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins_extra/SRR5936124_NanH_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5936124_NanH_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins_extra/SRR5936125_NanH_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5936125_NanH_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins_extra/SRR5936126_NanH_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5936126_NanH_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins_extra/SRR5936127_NanH_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5936127_NanH_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins_extra/SRR5936128_NanH_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5936128_NanH_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins_extra/SRR5936129_NanH_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5936129_NanH_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins_extra/SRR5936130_NanH_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5936130_NanH_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins_extra/SRR5936131_NanH_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5936131_NanH_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins_extra/SRR5936132_NanH_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5936132_NanH_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins_extra/SRR5936133_NanH_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5936133_NanH_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins_extra/SRR5936134_NanH_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5936134_NanH_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins_extra/SRR5936135_NanH_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5936135_NanH_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins_extra/SRR5936136_NanH_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5936136_NanH_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins_extra/SRR5936137_NanH_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5936137_NanH_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins_extra/SRR5936138_NanH_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5936138_NanH_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins_extra/SRR5936139_NanH_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5936139_NanH_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
