#!/bin/bash
#SBATCH --partition=SP2
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=8
#SBATCH -J lloyd_diamond_tax_extra_NanB_PM_1.sh
#SBATCH --mem=24042
#SBATCH --time=172:00:00
#OpenMP settings:
export OMP_NUM_THREADS=1
export MKL_NUM_THREADS=1
export OMP_PLACES=threads
export OMP_PROC_BIND=spread
echo $SLURM_JOB_ID
echo $SLURM_SUBMIT_DIR
echo $SLURM_JOB_NODELIST

srun diamond blastp -q ../aligned_proteins/SRR5935740_NanB_PM_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5935740_NanB_PM_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5935741_NanB_PM_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5935741_NanB_PM_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5935742_NanB_PM_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5935742_NanB_PM_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5935743_NanB_PM_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5935743_NanB_PM_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5935744_NanB_PM_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5935744_NanB_PM_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5935745_NanB_PM_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5935745_NanB_PM_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5935746_NanB_PM_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5935746_NanB_PM_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5935747_NanB_PM_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5935747_NanB_PM_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5935748_NanB_PM_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5935748_NanB_PM_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5935749_NanB_PM_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5935749_NanB_PM_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5935750_NanB_PM_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5935750_NanB_PM_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5935751_NanB_PM_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5935751_NanB_PM_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5935752_NanB_PM_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5935752_NanB_PM_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5935753_NanB_PM_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5935753_NanB_PM_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5935754_NanB_PM_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5935754_NanB_PM_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5935755_NanB_PM_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5935755_NanB_PM_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5935756_NanB_PM_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5935756_NanB_PM_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5935757_NanB_PM_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5935757_NanB_PM_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5935758_NanB_PM_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5935758_NanB_PM_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5935759_NanB_PM_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5935759_NanB_PM_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5935760_NanB_PM_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5935760_NanB_PM_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5935761_NanB_PM_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5935761_NanB_PM_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5935762_NanB_PM_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5935762_NanB_PM_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5935763_NanB_PM_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5935763_NanB_PM_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5935764_NanB_PM_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5935764_NanB_PM_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5935765_NanB_PM_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5935765_NanB_PM_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5935766_NanB_PM_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5935766_NanB_PM_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5935767_NanB_PM_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5935767_NanB_PM_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5935768_NanB_PM_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5935768_NanB_PM_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5935769_NanB_PM_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5935769_NanB_PM_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5935770_NanB_PM_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5935770_NanB_PM_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5935771_NanB_PM_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5935771_NanB_PM_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5935772_NanB_PM_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5935772_NanB_PM_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5935773_NanB_PM_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5935773_NanB_PM_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5935774_NanB_PM_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5935774_NanB_PM_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5935775_NanB_PM_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5935775_NanB_PM_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5935776_NanB_PM_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5935776_NanB_PM_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5935777_NanB_PM_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5935777_NanB_PM_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5935778_NanB_PM_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5935778_NanB_PM_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5935779_NanB_PM_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5935779_NanB_PM_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5935780_NanB_PM_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5935780_NanB_PM_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5935781_NanB_PM_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5935781_NanB_PM_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5935782_NanB_PM_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5935782_NanB_PM_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5935783_NanB_PM_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5935783_NanB_PM_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5935784_NanB_PM_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5935784_NanB_PM_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5935785_NanB_PM_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5935785_NanB_PM_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5935786_NanB_PM_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5935786_NanB_PM_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5935787_NanB_PM_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5935787_NanB_PM_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5935788_NanB_PM_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5935788_NanB_PM_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5935789_NanB_PM_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5935789_NanB_PM_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
