#!/bin/bash
#SBATCH --partition=SP2
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=8
#SBATCH -J lloyd_diamond_tax_extra_NanB_SP_26.sh
#SBATCH --mem=24042
#SBATCH --time=172:00:00
#OpenMP settings:
export OMP_NUM_THREADS=1
export MKL_NUM_THREADS=1
export OMP_PLACES=threads
export OMP_PROC_BIND=spread
echo $SLURM_JOB_ID
echo $SLURM_SUBMIT_DIR
echo $SLURM_JOB_NODELIST

srun diamond blastp -q ../aligned_proteins/SRR5950734_NanB_SP_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5950734_NanB_SP_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5950735_NanB_SP_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5950735_NanB_SP_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5950736_NanB_SP_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5950736_NanB_SP_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5950737_NanB_SP_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5950737_NanB_SP_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5950738_NanB_SP_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5950738_NanB_SP_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5950739_NanB_SP_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5950739_NanB_SP_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5950740_NanB_SP_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5950740_NanB_SP_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5950741_NanB_SP_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5950741_NanB_SP_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5950742_NanB_SP_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5950742_NanB_SP_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5950743_NanB_SP_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5950743_NanB_SP_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5950744_NanB_SP_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5950744_NanB_SP_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5950745_NanB_SP_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5950745_NanB_SP_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5950746_NanB_SP_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5950746_NanB_SP_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5950747_NanB_SP_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5950747_NanB_SP_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5950748_NanB_SP_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5950748_NanB_SP_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5950749_NanB_SP_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5950749_NanB_SP_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5950750_NanB_SP_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5950750_NanB_SP_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5950751_NanB_SP_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5950751_NanB_SP_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5950752_NanB_SP_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5950752_NanB_SP_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5950753_NanB_SP_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5950753_NanB_SP_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5950754_NanB_SP_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5950754_NanB_SP_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5950755_NanB_SP_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5950755_NanB_SP_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5950756_NanB_SP_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5950756_NanB_SP_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5950757_NanB_SP_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5950757_NanB_SP_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5950758_NanB_SP_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5950758_NanB_SP_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5950759_NanB_SP_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5950759_NanB_SP_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5950760_NanB_SP_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5950760_NanB_SP_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5950761_NanB_SP_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5950761_NanB_SP_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5950762_NanB_SP_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5950762_NanB_SP_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5950763_NanB_SP_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5950763_NanB_SP_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5950764_NanB_SP_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5950764_NanB_SP_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5950765_NanB_SP_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5950765_NanB_SP_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5950766_NanB_SP_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5950766_NanB_SP_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5950767_NanB_SP_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5950767_NanB_SP_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5950768_NanB_SP_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5950768_NanB_SP_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5950769_NanB_SP_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5950769_NanB_SP_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5950770_NanB_SP_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5950770_NanB_SP_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5950771_NanB_SP_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5950771_NanB_SP_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5950772_NanB_SP_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5950772_NanB_SP_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5950773_NanB_SP_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5950773_NanB_SP_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5950774_NanB_SP_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5950774_NanB_SP_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5950775_NanB_SP_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5950775_NanB_SP_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5950776_NanB_SP_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5950776_NanB_SP_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5950777_NanB_SP_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5950777_NanB_SP_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5950778_NanB_SP_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5950778_NanB_SP_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5950779_NanB_SP_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5950779_NanB_SP_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5950780_NanB_SP_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5950780_NanB_SP_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5950781_NanB_SP_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5950781_NanB_SP_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5950782_NanB_SP_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5950782_NanB_SP_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
srun diamond blastp -q ../aligned_proteins/SRR5950783_NanB_SP_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o SRR5950783_NanB_SP_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 8
