#!/bin/bash
#SBATCH --partition=SP2
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=4
#SBATCH -J smillie_diamond_tax_NeuB.sh
#SBATCH --mem=24042
#SBATCH --time=172:00:00
#OpenMP settings:
export OMP_NUM_THREADS=1
export MKL_NUM_THREADS=1
export OMP_PLACES=threads
export OMP_PROC_BIND=spread
echo $SLURM_JOB_ID
echo $SLURM_SUBMIT_DIR
echo $SLURM_JOB_NODELIST

srun diamond blastp -q ../aligned_proteins/ERR3607252_NeuB_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o ERR3607252_NeuB_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 4
srun diamond blastp -q ../aligned_proteins/ERR3607253_NeuB_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o ERR3607253_NeuB_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 4
srun diamond blastp -q ../aligned_proteins/ERR3607254_NeuB_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o ERR3607254_NeuB_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 4
srun diamond blastp -q ../aligned_proteins/ERR3607255_NeuB_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o ERR3607255_NeuB_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 4
srun diamond blastp -q ../aligned_proteins/ERR3607256_NeuB_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o ERR3607256_NeuB_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 4
srun diamond blastp -q ../aligned_proteins/ERR3607257_NeuB_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o ERR3607257_NeuB_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 4
srun diamond blastp -q ../aligned_proteins/ERR3607258_NeuB_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o ERR3607258_NeuB_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 4
srun diamond blastp -q ../aligned_proteins/ERR3607259_NeuB_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o ERR3607259_NeuB_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 4
srun diamond blastp -q ../aligned_proteins/ERR3607260_NeuB_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o ERR3607260_NeuB_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 4
srun diamond blastp -q ../aligned_proteins/ERR3607261_NeuB_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o ERR3607261_NeuB_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 4
srun diamond blastp -q ../aligned_proteins/ERR3607262_NeuB_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o ERR3607262_NeuB_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 4
srun diamond blastp -q ../aligned_proteins/ERR3607263_NeuB_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o ERR3607263_NeuB_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 4
srun diamond blastp -q ../aligned_proteins/ERR3607264_NeuB_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o ERR3607264_NeuB_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 4
srun diamond blastp -q ../aligned_proteins/ERR3607265_NeuB_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o ERR3607265_NeuB_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 4
srun diamond blastp -q ../aligned_proteins/ERR3607266_NeuB_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o ERR3607266_NeuB_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 4
srun diamond blastp -q ../aligned_proteins/ERR3607267_NeuB_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o ERR3607267_NeuB_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 4
srun diamond blastp -q ../aligned_proteins/ERR3607268_NeuB_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o ERR3607268_NeuB_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 4
srun diamond blastp -q ../aligned_proteins/ERR3607269_NeuB_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o ERR3607269_NeuB_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 4
srun diamond blastp -q ../aligned_proteins/ERR3607270_NeuB_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o ERR3607270_NeuB_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 4
srun diamond blastp -q ../aligned_proteins/ERR3607271_NeuB_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o ERR3607271_NeuB_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 4
srun diamond blastp -q ../aligned_proteins/ERR3607272_NeuB_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o ERR3607272_NeuB_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 4
srun diamond blastp -q ../aligned_proteins/ERR3607273_NeuB_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o ERR3607273_NeuB_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 4
srun diamond blastp -q ../aligned_proteins/ERR3607274_NeuB_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o ERR3607274_NeuB_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 4
srun diamond blastp -q ../aligned_proteins/ERR3607275_NeuB_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o ERR3607275_NeuB_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 4
srun diamond blastp -q ../aligned_proteins/ERR3607276_NeuB_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o ERR3607276_NeuB_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 4
srun diamond blastp -q ../aligned_proteins/ERR3607277_NeuB_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o ERR3607277_NeuB_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 4
srun diamond blastp -q ../aligned_proteins/ERR3607278_NeuB_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o ERR3607278_NeuB_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 4
srun diamond blastp -q ../aligned_proteins/ERR3607279_NeuB_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o ERR3607279_NeuB_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 4
srun diamond blastp -q ../aligned_proteins/ERR3607280_NeuB_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o ERR3607280_NeuB_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 4
srun diamond blastp -q ../aligned_proteins/ERR3607281_NeuB_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o ERR3607281_NeuB_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 4
srun diamond blastp -q ../aligned_proteins/ERR3607282_NeuB_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o ERR3607282_NeuB_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 4
srun diamond blastp -q ../aligned_proteins/ERR3607283_NeuB_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o ERR3607283_NeuB_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 4
srun diamond blastp -q ../aligned_proteins/ERR3607284_NeuB_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o ERR3607284_NeuB_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 4
srun diamond blastp -q ../aligned_proteins/ERR3607285_NeuB_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o ERR3607285_NeuB_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 4
srun diamond blastp -q ../aligned_proteins/ERR3607286_NeuB_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o ERR3607286_NeuB_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 4
srun diamond blastp -q ../aligned_proteins/ERR3607287_NeuB_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o ERR3607287_NeuB_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 4
srun diamond blastp -q ../aligned_proteins/ERR3607288_NeuB_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o ERR3607288_NeuB_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 4
srun diamond blastp -q ../aligned_proteins/ERR3607289_NeuB_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o ERR3607289_NeuB_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 4
srun diamond blastp -q ../aligned_proteins/ERR3607290_NeuB_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o ERR3607290_NeuB_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 4
srun diamond blastp -q ../aligned_proteins/ERR3607291_NeuB_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o ERR3607291_NeuB_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 4
srun diamond blastp -q ../aligned_proteins/ERR3607292_NeuB_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o ERR3607292_NeuB_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 4
srun diamond blastp -q ../aligned_proteins/ERR3607293_NeuB_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o ERR3607293_NeuB_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 4
srun diamond blastp -q ../aligned_proteins/ERR3607294_NeuB_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o ERR3607294_NeuB_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 4
srun diamond blastp -q ../aligned_proteins/ERR3607295_NeuB_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o ERR3607295_NeuB_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 4
srun diamond blastp -q ../aligned_proteins/ERR3607296_NeuB_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o ERR3607296_NeuB_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 4
srun diamond blastp -q ../aligned_proteins/ERR3607297_NeuB_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o ERR3607297_NeuB_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 4
srun diamond blastp -q ../aligned_proteins/ERR3607298_NeuB_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o ERR3607298_NeuB_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 4
srun diamond blastp -q ../aligned_proteins/ERR3607299_NeuB_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o ERR3607299_NeuB_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 4
srun diamond blastp -q ../aligned_proteins/ERR3607300_NeuB_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o ERR3607300_NeuB_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 4
srun diamond blastp -q ../aligned_proteins/ERR3607301_NeuB_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o ERR3607301_NeuB_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 4
srun diamond blastp -q ../aligned_proteins/ERR3607302_NeuB_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o ERR3607302_NeuB_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 4
srun diamond blastp -q ../aligned_proteins/ERR3607303_NeuB_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o ERR3607303_NeuB_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 4
srun diamond blastp -q ../aligned_proteins/ERR3607304_NeuB_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o ERR3607304_NeuB_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 4
srun diamond blastp -q ../aligned_proteins/ERR3607305_NeuB_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o ERR3607305_NeuB_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 4
srun diamond blastp -q ../aligned_proteins/ERR3607306_NeuB_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o ERR3607306_NeuB_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 4
srun diamond blastp -q ../aligned_proteins/ERR3607307_NeuB_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o ERR3607307_NeuB_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 4
srun diamond blastp -q ../aligned_proteins/ERR3607308_NeuB_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o ERR3607308_NeuB_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 4
srun diamond blastp -q ../aligned_proteins/ERR3607309_NeuB_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o ERR3607309_NeuB_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 4
srun diamond blastp -q ../aligned_proteins/ERR3607310_NeuB_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o ERR3607310_NeuB_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 4
srun diamond blastp -q ../aligned_proteins/ERR3607311_NeuB_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o ERR3607311_NeuB_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 4
srun diamond blastp -q ../aligned_proteins/ERR3607312_NeuB_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o ERR3607312_NeuB_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 4
srun diamond blastp -q ../aligned_proteins/ERR3722005_NeuB_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o ERR3722005_NeuB_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 4
srun diamond blastp -q ../aligned_proteins/ERR3722006_NeuB_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o ERR3722006_NeuB_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 4
srun diamond blastp -q ../aligned_proteins/ERR3722007_NeuB_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o ERR3722007_NeuB_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 4
srun diamond blastp -q ../aligned_proteins/ERR3722008_NeuB_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o ERR3722008_NeuB_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 4
srun diamond blastp -q ../aligned_proteins/ERR3722009_NeuB_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o ERR3722009_NeuB_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 4
srun diamond blastp -q ../aligned_proteins/ERR3722010_NeuB_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o ERR3722010_NeuB_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 4
srun diamond blastp -q ../aligned_proteins/ERR3722011_NeuB_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o ERR3722011_NeuB_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 4
srun diamond blastp -q ../aligned_proteins/ERR3722012_NeuB_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o ERR3722012_NeuB_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 4
srun diamond blastp -q ../aligned_proteins/ERR3722013_NeuB_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o ERR3722013_NeuB_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 4
srun diamond blastp -q ../aligned_proteins/ERR3722014_NeuB_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o ERR3722014_NeuB_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 4
srun diamond blastp -q ../aligned_proteins/ERR3722015_NeuB_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o ERR3722015_NeuB_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 4
srun diamond blastp -q ../aligned_proteins/ERR3722016_NeuB_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o ERR3722016_NeuB_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 4
srun diamond blastp -q ../aligned_proteins/ERR3722017_NeuB_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o ERR3722017_NeuB_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 4
srun diamond blastp -q ../aligned_proteins/ERR3722018_NeuB_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o ERR3722018_NeuB_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 4
srun diamond blastp -q ../aligned_proteins/ERR3722019_NeuB_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o ERR3722019_NeuB_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 4
srun diamond blastp -q ../aligned_proteins/ERR3722020_NeuB_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o ERR3722020_NeuB_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 4
srun diamond blastp -q ../aligned_proteins/ERR3722021_NeuB_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o ERR3722021_NeuB_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 4
srun diamond blastp -q ../aligned_proteins/ERR3722022_NeuB_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o ERR3722022_NeuB_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 4
srun diamond blastp -q ../aligned_proteins/ERR3722023_NeuB_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o ERR3722023_NeuB_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 4
srun diamond blastp -q ../aligned_proteins/ERR3722024_NeuB_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o ERR3722024_NeuB_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 4
srun diamond blastp -q ../aligned_proteins/ERR3722025_NeuB_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o ERR3722025_NeuB_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 4
srun diamond blastp -q ../aligned_proteins/ERR3722026_NeuB_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o ERR3722026_NeuB_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 4
srun diamond blastp -q ../aligned_proteins/ERR3722027_NeuB_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o ERR3722027_NeuB_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 4
srun diamond blastp -q ../aligned_proteins/ERR3722028_NeuB_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o ERR3722028_NeuB_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 4
srun diamond blastp -q ../aligned_proteins/ERR3722029_NeuB_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o ERR3722029_NeuB_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 4
srun diamond blastp -q ../aligned_proteins/ERR3722030_NeuB_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o ERR3722030_NeuB_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 4
