#!/bin/bash
#SBATCH --partition=SP2
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=4
#SBATCH -J smillie_diamond_tax_SatC.sh
#SBATCH --mem=24042
#SBATCH --time=172:00:00
#OpenMP settings:
export OMP_NUM_THREADS=1
export MKL_NUM_THREADS=1
export OMP_PLACES=threads
export OMP_PROC_BIND=spread
echo $SLURM_JOB_ID
echo $SLURM_SUBMIT_DIR
echo $SLURM_JOB_NODELIST

srun diamond blastp -q ../aligned_proteins/ERR3607252_SatC_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o ERR3607252_SatC_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 4
srun diamond blastp -q ../aligned_proteins/ERR3607253_SatC_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o ERR3607253_SatC_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 4
srun diamond blastp -q ../aligned_proteins/ERR3607254_SatC_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o ERR3607254_SatC_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 4
srun diamond blastp -q ../aligned_proteins/ERR3607255_SatC_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o ERR3607255_SatC_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 4
srun diamond blastp -q ../aligned_proteins/ERR3607256_SatC_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o ERR3607256_SatC_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 4
srun diamond blastp -q ../aligned_proteins/ERR3607257_SatC_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o ERR3607257_SatC_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 4
srun diamond blastp -q ../aligned_proteins/ERR3607258_SatC_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o ERR3607258_SatC_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 4
srun diamond blastp -q ../aligned_proteins/ERR3607259_SatC_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o ERR3607259_SatC_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 4
srun diamond blastp -q ../aligned_proteins/ERR3607260_SatC_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o ERR3607260_SatC_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 4
srun diamond blastp -q ../aligned_proteins/ERR3607261_SatC_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o ERR3607261_SatC_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 4
srun diamond blastp -q ../aligned_proteins/ERR3607262_SatC_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o ERR3607262_SatC_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 4
srun diamond blastp -q ../aligned_proteins/ERR3607263_SatC_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o ERR3607263_SatC_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 4
srun diamond blastp -q ../aligned_proteins/ERR3607264_SatC_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o ERR3607264_SatC_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 4
srun diamond blastp -q ../aligned_proteins/ERR3607265_SatC_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o ERR3607265_SatC_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 4
srun diamond blastp -q ../aligned_proteins/ERR3607266_SatC_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o ERR3607266_SatC_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 4
srun diamond blastp -q ../aligned_proteins/ERR3607267_SatC_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o ERR3607267_SatC_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 4
srun diamond blastp -q ../aligned_proteins/ERR3607268_SatC_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o ERR3607268_SatC_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 4
srun diamond blastp -q ../aligned_proteins/ERR3607269_SatC_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o ERR3607269_SatC_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 4
srun diamond blastp -q ../aligned_proteins/ERR3607270_SatC_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o ERR3607270_SatC_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 4
srun diamond blastp -q ../aligned_proteins/ERR3607271_SatC_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o ERR3607271_SatC_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 4
srun diamond blastp -q ../aligned_proteins/ERR3607272_SatC_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o ERR3607272_SatC_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 4
srun diamond blastp -q ../aligned_proteins/ERR3607273_SatC_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o ERR3607273_SatC_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 4
srun diamond blastp -q ../aligned_proteins/ERR3607274_SatC_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o ERR3607274_SatC_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 4
srun diamond blastp -q ../aligned_proteins/ERR3607275_SatC_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o ERR3607275_SatC_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 4
srun diamond blastp -q ../aligned_proteins/ERR3607276_SatC_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o ERR3607276_SatC_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 4
srun diamond blastp -q ../aligned_proteins/ERR3607277_SatC_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o ERR3607277_SatC_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 4
srun diamond blastp -q ../aligned_proteins/ERR3607278_SatC_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o ERR3607278_SatC_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 4
srun diamond blastp -q ../aligned_proteins/ERR3607279_SatC_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o ERR3607279_SatC_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 4
srun diamond blastp -q ../aligned_proteins/ERR3607280_SatC_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o ERR3607280_SatC_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 4
srun diamond blastp -q ../aligned_proteins/ERR3607281_SatC_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o ERR3607281_SatC_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 4
srun diamond blastp -q ../aligned_proteins/ERR3607282_SatC_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o ERR3607282_SatC_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 4
srun diamond blastp -q ../aligned_proteins/ERR3607283_SatC_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o ERR3607283_SatC_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 4
srun diamond blastp -q ../aligned_proteins/ERR3607284_SatC_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o ERR3607284_SatC_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 4
srun diamond blastp -q ../aligned_proteins/ERR3607285_SatC_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o ERR3607285_SatC_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 4
srun diamond blastp -q ../aligned_proteins/ERR3607286_SatC_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o ERR3607286_SatC_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 4
srun diamond blastp -q ../aligned_proteins/ERR3607287_SatC_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o ERR3607287_SatC_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 4
srun diamond blastp -q ../aligned_proteins/ERR3607288_SatC_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o ERR3607288_SatC_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 4
srun diamond blastp -q ../aligned_proteins/ERR3607289_SatC_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o ERR3607289_SatC_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 4
srun diamond blastp -q ../aligned_proteins/ERR3607290_SatC_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o ERR3607290_SatC_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 4
srun diamond blastp -q ../aligned_proteins/ERR3607291_SatC_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o ERR3607291_SatC_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 4
srun diamond blastp -q ../aligned_proteins/ERR3607292_SatC_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o ERR3607292_SatC_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 4
srun diamond blastp -q ../aligned_proteins/ERR3607293_SatC_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o ERR3607293_SatC_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 4
srun diamond blastp -q ../aligned_proteins/ERR3607294_SatC_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o ERR3607294_SatC_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 4
srun diamond blastp -q ../aligned_proteins/ERR3607295_SatC_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o ERR3607295_SatC_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 4
srun diamond blastp -q ../aligned_proteins/ERR3607296_SatC_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o ERR3607296_SatC_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 4
srun diamond blastp -q ../aligned_proteins/ERR3607297_SatC_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o ERR3607297_SatC_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 4
srun diamond blastp -q ../aligned_proteins/ERR3607298_SatC_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o ERR3607298_SatC_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 4
srun diamond blastp -q ../aligned_proteins/ERR3607299_SatC_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o ERR3607299_SatC_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 4
srun diamond blastp -q ../aligned_proteins/ERR3607300_SatC_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o ERR3607300_SatC_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 4
srun diamond blastp -q ../aligned_proteins/ERR3607301_SatC_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o ERR3607301_SatC_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 4
srun diamond blastp -q ../aligned_proteins/ERR3607302_SatC_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o ERR3607302_SatC_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 4
srun diamond blastp -q ../aligned_proteins/ERR3607303_SatC_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o ERR3607303_SatC_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 4
srun diamond blastp -q ../aligned_proteins/ERR3607304_SatC_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o ERR3607304_SatC_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 4
srun diamond blastp -q ../aligned_proteins/ERR3607305_SatC_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o ERR3607305_SatC_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 4
srun diamond blastp -q ../aligned_proteins/ERR3607306_SatC_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o ERR3607306_SatC_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 4
srun diamond blastp -q ../aligned_proteins/ERR3607307_SatC_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o ERR3607307_SatC_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 4
srun diamond blastp -q ../aligned_proteins/ERR3607308_SatC_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o ERR3607308_SatC_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 4
srun diamond blastp -q ../aligned_proteins/ERR3607309_SatC_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o ERR3607309_SatC_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 4
srun diamond blastp -q ../aligned_proteins/ERR3607310_SatC_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o ERR3607310_SatC_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 4
srun diamond blastp -q ../aligned_proteins/ERR3607311_SatC_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o ERR3607311_SatC_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 4
srun diamond blastp -q ../aligned_proteins/ERR3607312_SatC_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o ERR3607312_SatC_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 4
srun diamond blastp -q ../aligned_proteins/ERR3722005_SatC_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o ERR3722005_SatC_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 4
srun diamond blastp -q ../aligned_proteins/ERR3722006_SatC_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o ERR3722006_SatC_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 4
srun diamond blastp -q ../aligned_proteins/ERR3722007_SatC_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o ERR3722007_SatC_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 4
srun diamond blastp -q ../aligned_proteins/ERR3722008_SatC_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o ERR3722008_SatC_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 4
srun diamond blastp -q ../aligned_proteins/ERR3722009_SatC_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o ERR3722009_SatC_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 4
srun diamond blastp -q ../aligned_proteins/ERR3722010_SatC_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o ERR3722010_SatC_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 4
srun diamond blastp -q ../aligned_proteins/ERR3722011_SatC_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o ERR3722011_SatC_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 4
srun diamond blastp -q ../aligned_proteins/ERR3722012_SatC_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o ERR3722012_SatC_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 4
srun diamond blastp -q ../aligned_proteins/ERR3722013_SatC_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o ERR3722013_SatC_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 4
srun diamond blastp -q ../aligned_proteins/ERR3722014_SatC_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o ERR3722014_SatC_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 4
srun diamond blastp -q ../aligned_proteins/ERR3722015_SatC_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o ERR3722015_SatC_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 4
srun diamond blastp -q ../aligned_proteins/ERR3722016_SatC_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o ERR3722016_SatC_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 4
srun diamond blastp -q ../aligned_proteins/ERR3722017_SatC_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o ERR3722017_SatC_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 4
srun diamond blastp -q ../aligned_proteins/ERR3722018_SatC_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o ERR3722018_SatC_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 4
srun diamond blastp -q ../aligned_proteins/ERR3722019_SatC_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o ERR3722019_SatC_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 4
srun diamond blastp -q ../aligned_proteins/ERR3722020_SatC_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o ERR3722020_SatC_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 4
srun diamond blastp -q ../aligned_proteins/ERR3722021_SatC_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o ERR3722021_SatC_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 4
srun diamond blastp -q ../aligned_proteins/ERR3722022_SatC_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o ERR3722022_SatC_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 4
srun diamond blastp -q ../aligned_proteins/ERR3722023_SatC_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o ERR3722023_SatC_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 4
srun diamond blastp -q ../aligned_proteins/ERR3722024_SatC_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o ERR3722024_SatC_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 4
srun diamond blastp -q ../aligned_proteins/ERR3722025_SatC_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o ERR3722025_SatC_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 4
srun diamond blastp -q ../aligned_proteins/ERR3722026_SatC_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o ERR3722026_SatC_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 4
srun diamond blastp -q ../aligned_proteins/ERR3722027_SatC_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o ERR3722027_SatC_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 4
srun diamond blastp -q ../aligned_proteins/ERR3722028_SatC_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o ERR3722028_SatC_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 4
srun diamond blastp -q ../aligned_proteins/ERR3722029_SatC_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o ERR3722029_SatC_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 4
srun diamond blastp -q ../aligned_proteins/ERR3722030_SatC_proteins_aligned.faa -d ../../nr-faa/nr_diamond -o ERR3722030_SatC_diamond_tax.tsv --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --max-target-seqs 10 --evalue 1e-5 --threads 4
